### ISSUE TITLE
Upgrade to OCaml 5.0.0

### ISSUE THREAD

**Issue by nicokn** [goblint/analyzer#1003]
Upgrade to OCaml 5.0.0 to support new language features e.g., [shared memory parallelism](https://v2.ocaml.org/releases/5.0/manual/parallelism.html).

List of tasks for goblint/analyzer

- [x] mlgmpodl 1.2.14 -> 1.2.15 (not yet in opam, https://github.com/nberth/mlgmpidl/issues/17)
- [x] ocaml-config 2 -> 3 
- [x] apron v0.9.13 -> latest (https://github.com/ocaml/opam-repository/pull/24090)

List of tasks for goblint/gobview

- [x] jsoo-react.dev -> latest

**Comment by FeldrinH** [comment]
mlgmpodl 1.2.15 is now on opam. Hopefully apron will follow soon (https://github.com/antoinemine/apron/issues/89).

**Comment by sim642** [comment]
Actually Apron is already in the pipeline as well: https://github.com/ocaml/opam-repository/pull/24090.

**Comment by sim642** [comment]
I'll close this as all our dependencies are available under OCaml 5.0 now and Goblint does work. However, as discovered in #1137, there are some performance regressions to be investigated before we can use OCaml 5.0 as the default. But that's a separate challenge.
