### ISSUE TITLE
Soundness issue related to `invariant` and `lognot`

### ISSUE THREAD

**Issue by michael-schwarz** [goblint/analyzer#103]
**Follow-up to #90 and #92. We discussed a similar issue there.**

In this example, we unsoundly claim that `x==1` in the else branch. However, the only value that we should be able to exclude here is `0`, as any value `!x` is false for every value that is not `0`. This problem happens both with `def_exc` and `interval`. Test are in the `branching_lognot` branch.

https://github.com/goblint/analyzer/blob/8b612b3066f776cf39f1fe9ea538b358056f9216/tests/regression/27-inv_invariants/03-ints-not.c#L1-L9

Spotted by our student @Fyanzar, thx!

**Comment by vogler** [comment]
`invariant` calls `ID.lognot` for `ID.of_excl_list ik [Int64.zero]`, so the problem should be in `IntDomain`.

**Comment by michael-schwarz** [comment]
I don't think so: e.g.
https://github.com/goblint/analyzer/blob/8b612b3066f776cf39f1fe9ea538b358056f9216/src/cdomains/intDomain.ml#L904

in `Def_Exc` seems to be exactly the right thing. It is just restricting with this that is wrong.

**Comment by vogler** [comment]
`eq` calls `of_bool false` which gives 0, which is ok for `lognot`. The problem is that `!` always gives `0` or `1`, so it's not invertible and we can't use `lognot`.
