### ISSUE TITLE
Building goblint

### ISSUE THREAD

**Issue by buddybu** [goblint/analyzer#1034]
I am attempting to build from within a debian docker container, but I am getting a hanging situation when running the 'make setup' command.  

I have the specified required tools and libraries installed.  I have tried the latest code as well as the 2.1.0 release, both are failing to complete setup.  The process just sits at:

Processing 91/213: [conf-gmp:sh] [ocaml-base-compiler: ./configure]

I have tried to just execute the command line on the development version (pulled from master)

opam switch -y create . --deps-only ocaml-variants,4.14.0+options ocaml-option-flambda --locked --jobs=1 

I have also tried the command line on the 2.1.0 release:
opam switch -y create . --deps-only ocaml-base-compiler.4.14.0 --locked --jobs=1

To see if it was a dependency situation with paralallism, but both stop with Processing xx/yyy: [conf-gmp: sh]

Any suggestions?

**Comment by buddybu** [comment]
Discovered it was a toolset issue.

**Comment by sim642** [comment]
Here's what the conf-gmp package in the opam repository is executing to check the availability of GMP (completely independent of Goblint): https://github.com/ocaml/opam-repository/blob/1853726ac7f8449674c8bc6bc54288ad5f58b857/packages/conf-gmp/conf-gmp.4/opam#L7.

If `cc` isn't just a symlink to `gcc`, then what is it in the Debian docker image?

By the way, this repository has its own Dockerfile as well, which is built nightly as well.

**Comment by michael-schwarz** [comment]
@buddybu were you able to resolve the issue? is there anything else we can help with?

**Comment by buddybu** [comment]
I have not resolved this yet, but have been pulled into other priorities.  Please keep this open, as I will come back to it.

**Comment by buddybu** [comment]
You can close. I am still off on other things
