### ISSUE TITLE
Privatizations unsound when enabling the `thread` analysis

### ISSUE THREAD

**Issue by michael-schwarz** [goblint/analyzer#1043]
While playing around with examples to discover what we want to do for phases, I discovered (some of) the privatizations are unsound after enabling the `thread` analysis from `threadAnalysis.ml`.

~~~C
// PARAM: --set ana.path_sens[+] threadflag --set ana.base.privatization mutex-meet-tid --enable ana.int.interval --set ana.activated[+] threadJoins --set ana.activated[+] thread
#include <pthread.h>
#include <goblint.h>

int g = 10;

pthread_mutex_t A = PTHREAD_MUTEX_INITIALIZER;

void *t_benign(void *arg) {
  pthread_mutex_lock(&A);
  g = 10;
  __goblint_check(g == 10);
  pthread_mutex_unlock(&A);
  return NULL;
}

void *t_benign2(void *arg) {
  pthread_mutex_lock(&A);
  __goblint_check(g == 20);
  g = 10;
  __goblint_check(g == 10);
  pthread_mutex_unlock(&A);
  return NULL;
}

int main(void) {

  pthread_t id2;
  pthread_create(&id2, NULL, t_benign, NULL);
  pthread_join(id2, NULL);


  g = 20;
  __goblint_check(g == 20);


  pthread_create(&id2, NULL, t_benign2, NULL);


  pthread_mutex_lock(&A);
  __goblint_check(g == 20); //UNKNOWN!
  pthread_mutex_unlock(&A);

  return 0;
}
~~~

Here, the analysis claims to know that the value of `g` is always `10` in `t_benign2` and in `main` after `t_benign2` is created.

The issue seems to be that the `thread` analysis answers that in the place where `g` is written the analysis is in single-threaded mode again (as `t_benign` exited cleanly). However., the privatizations do not properly support going back to single-threaded mode and then back to multi-threaded mode later.

**Comment by sim642** [comment]
This is also loosely related to #860.
