### ISSUE TITLE
Escaped variables are not communicated between threads

### ISSUE THREAD

**Issue by jerhard** [goblint/analyzer#1074]
In [this test case](
https://github.com/goblint/analyzer/blob/8dcc0b00406839ce0782e52132f91a4ec06a7629/tests/regression/74-escape/01-local-esacpe.c), Goblint, with the default configuration, does not relax information about the escaped local variables `x`, even though another thread may be writing into it. In particular, Goblint unsoundly claims that the second `__goblint_check` will succeed:

https://github.com/goblint/analyzer/blob/8dcc0b00406839ce0782e52132f91a4ec06a7629/tests/regression/74-escape/01-local-esacpe.c#L9-L17

**Comment by jerhard** [comment]
When `*p` is written in `thread2`, it the Base analysis knows that `p` may point to `x`, however `is_global ask x`  returns false. This is due to the `ThreadEscape` analysis claiming that `x` has not escaped. 

For the `MayEscape x`   query, the `ThreadEscape` analysis looks up whether `x` is in its local state. But `x` escaped in `thread1`, and there seems to be no synchronization of this information to the analysis of `thread2`. So one somehow needs to answer the `MayEscape` queries based on some flow-insensitive-invariant. 
There may be some ways to   avoid being completely flow-insensitive by excluding some escapes that definitely have not happened yet: e.g. when there is a unique thread, a local variable of it must have escaped in its own past.
@michael-schwarz and I discussed some of this shortly yesterday.

**Comment by sim642** [comment]
In #686 we already added a global invariant to the threadescape analysis. Do you know why that doesn't already account for this?

**Comment by jerhard** [comment]
In the current state of the analysis, there is no `ctx.getg`, i.e. things that are side-effected are never considered, also not when answering queries.
