### ISSUE TITLE
Remove `MapDomain.Groupable`

### ISSUE THREAD

**Issue by sim642** [goblint/analyzer#1097]
`MapDomain` keys require more than just a `Printable.S`, which is constantly annoying:
https://github.com/goblint/analyzer/blob/a651cccf69af65581222d7e8e046b8ad67510cf4/src/domains/mapDomain.ml#L58-L65
AFAIK only base analysis' `CPA` uses non-trivial grouping and just in its debug `pretty` printing (not even in XML), so the grouped printing code could just be specialized in `CPA` while all other uses of `MapDomain` avoid the extra complication.

**Comment by michael-schwarz** [comment]
Good idea!
