### ISSUE TITLE
Goblint throws a ParseError when analyzing Linux 6.2

### ISSUE THREAD

**Issue by tluio** [goblint/analyzer#1098]
I first use `bear -- make` to compile the Linux kernel and get compile_commands.json.
And then run `goblint compile_commands.json` to analyze the kernel.
However, I got the following error:

```
REDOREDOREDOREDOlinux-6.2/arch/x86/include/asm/jump_label.h[27:0-0] : syntax error
Parsing errorFatal error: exception Goblint_lib__Maingoblint.FrontendError("Frontc.ParseError: Parse error")
Command exited with non-zero status 2
```

Any feedback will be appreciate!

**Comment by sim642** [comment]
Unfortunately that's not supported by our CIL parser. See https://github.com/goblint/cil/issues/81 for more info.
