### ISSUE TITLE
Add __VERIFIER_atomic_{begin,end} support

### ISSUE THREAD

**Issue by sim642** [goblint/analyzer#113]
[SV-COMP rules](https://sv-comp.sosy-lab.org/2021/rules.php):

> **`__VERIFIER_atomic_begin()`**: For modeling an atomic execution of a sequence of statements in a multi-threaded run-time environment, those statements can be placed between two function calls `__VERIFIER_atomic_begin()` and `__VERIFIER_atomic_end()` (deprecated but still valid: those statements can be placed in a function whose name matches `__VERIFIER_atomic_`). The verifiers are instructed to assume that the execution between those calls is not interrupted. The two calls need to occur within the same control-flow block; nesting or interleaving of those function calls is not allowed.

---

Importantly, the two functions cannot simply correspond to locking and unlocking some special atomic lock, because such atomic block must also not interfere with any single statement outside of an atomic block.

**Comment by michael-schwarz** [comment]
I think one possible way to this is to add some special lock that is acquired before such a block and released after.
Now, the check if a variable is public should be modified to always return false if this special lock is held:

https://github.com/goblint/analyzer/blob/50a72094ff13b87b3d4b55d4c58a36c0e70c4913/src/analyses/mutexAnalysis.ml#L158-L167

This means we privatize everything inside of these `__VERIFIER_atomic` and only generate side-effects when this block is over.
