### ISSUE TITLE
ValueDomain cast assertions in SV-COMP SoftwareSystems

### ISSUE THREAD

**Issue by sim642** [goblint/analyzer#117]
In my own run of Goblint on SV-COMP SoftwareSystems category, Goblint crashed with

```
exception File "src/cdomains/valueDomain.ml", line 350, characters 32-38: Assertion failed
```

https://github.com/goblint/analyzer/blob/3164939e27b7908839fe083f036ca165eb54d7ea/src/cdomains/valueDomain.ml#L350

on the following benchmarks:

- [x] ldv-commit-tester/m0_drivers-media-video-cx88-cx88-blackbird-ko--32_7a--d47b389-1.i
- [x] ldv-commit-tester/m0_drivers-media-video-cx88-cx88-blackbird-ko--32_7a--d47b389.i
- [x] ldv-linux-3.16-rc1/205_9a_array_safes_linux-3.16-rc1.tar.xz-205_9a-drivers--net--can--usb--peak_usb--peak_usb.ko-entry_point.cil.out.i
- [x] ldv-linux-3.16-rc1/205_9a_array_unsafes_linux-3.16-rc1.tar.xz-205_9a-drivers--net--wireless--rsi--rsi_91x.ko-entry_point.cil.out.i
- [x] ldv-linux-3.16-rc1/43_2a_consumption_linux-3.16-rc1.tar.xz-43_2a-drivers--net--ethernet--mellanox--mlx4--mlx4_en.ko-entry_point.cil.out.i
- [x] ldv-linux-3.16-rc1/43_2a_consumption_linux-3.16-rc1.tar.xz-43_2a-drivers--usb--host--xhci-hcd.ko-entry_point.cil.out.i
- [x] ldv-linux-3.16-rc1/43_2a_consumption_linux-3.16-rc1.tar.xz-43_2a-drivers--usb--host--xhci-hcd.ko-entry_point_-test.cil.out.i
- [x] ldv-validator-v0.6/linux-stable-1575714-1-150_1a-drivers--net--wireless--b43--b43.ko-entry_point.cil.out.i
- [x] ldv-validator-v0.6/linux-stable-d47b389-1-32_7a-drivers--media--video--cx88--cx88-blackbird.ko-entry_point.cil.out.i
- [x] ldv-linux-3.14/linux-3.14_linux-alloc-spinlock_drivers-net-wireless-b43legacy-b43legacy.cil.i
- [x] ldv-linux-3.14/linux-3.14_linux-drivers-clk1_drivers-net-wireless-b43legacy-b43legacy.cil.i
- [x] ldv-linux-3.14/linux-3.14_linux-kernel-locking-mutex_drivers-net-wireless-b43legacy-b43legacy.cil.i
- [x] ldv-linux-3.14/linux-3.14_linux-usb-dev_drivers-net-wireless-b43legacy-b43legacy.cil.i
- [x] ldv-challenges/linux-3.14_linux-kernel-locking-spinlock_drivers-net-wireless-b43legacy-b43legacy.cil.i
- [x] ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--gpu--drm--qxl--qxl.ko.cil.i
- [x] ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--scsi--BusLogic.ko.cil.i
- [x] ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--scsi--esas2r--esas2r.ko.cil.i

**Comment by vogler** [comment]
Could you run it with `--trace cast` and check what it's casting to in the log_top output?

**Comment by sim642** [comment]
For the first one at least, it ends with

```
%% cast: (../sv-benchmarks/c/ldv-commit-tester/m0_drivers-media-video-cx88-cx88-blackbird-ko--32_7a--d47b389-1.i:5549)
  log_top at 350: {&vargs[def_exc:0; 32bit intervals:[0,0]]} to __builtin_va_list  is top!
About to crash on ../sv-benchmarks/c/ldv-commit-tester/m0_drivers-media-video-cx88-cx88-blackbird-ko--32_7a--d47b389-1.i:5549
Fatal error: exception File "src/cdomains/valueDomain.ml", line 350, characters 32-38: Assertion failed
```

**Comment by vogler** [comment]
Ok, then a cast to `TBuiltin_va_list ` from http://cil-project.github.io/cil/doc/html/cil/api/Cil.html#TYPEtyp should be handled as well. Is there something better than going to `Top`? Is it a pointer?

**Comment by sim642** [comment]
Normal varargs usage doesn't even invoke this problem, only in SV-COMP preprocessed benchmarks where some GCC-specific macros are expanded types end up differing and CIL inserts casts. Since we don't handle varargs anyway, going to top makes no difference.
