### ISSUE TITLE
Infinity handled unsoundly for cosinus and sinus

### ISSUE THREAD

**Issue by stilscher** [goblint/analyzer#1273]
`cos` and `sin` both return NaN if the argument is + or - infinity. The implementation of cosinus and sinus in the float domain, however, only distinguishes the case where the argument is definitely infinity. In addition to that, one should also consider the case where the interval may contain an infinity.

**Comment by michael-schwarz** [comment]
Was this fixed as part of #1277?

**Comment by michael-schwarz** [comment]
I added tests on master for this now.
