### ISSUE TITLE
Investigate using `sarif` opam package

### ISSUE THREAD

**Issue by michael-schwarz** [goblint/analyzer#1321]
There is now a  package for `sarif` on opam. 
https://discuss.ocaml.org/t/ann-sarif-0-1-0-static-analysis-results-interchange-format-sarif-for-ocaml/13821 and https://gborough.github.io/sarif/sarif/sarif/index.html

Might be worth investigating if depending on this will allow use to reduce the amount of code we maintain ourselves.

**Comment by michael-schwarz** [comment]
They seem to depend on `core` though, not sure if we want to have dependencies on `core` and `batteries` at the same time.

**Comment by sim642** [comment]
Our `SarifType` module is just 120 lines, so it's probably not worth it. The package makes more sense if we'd use a larger portion of SARIF.
