### ISSUE TITLE
Floating-point C stubs violate OCaml GC rules

### ISSUE THREAD

**Issue by sim642** [goblint/analyzer#1371]
Our `FloatOps` C stubs are implemented like https://github.com/goblint/analyzer/blob/f2f5cc179c1965d909e6a984568ef43134b27123/src/common/cdomains/floatOps/stubs.c#L39-L48

These violate GC rules set out by OCaml documentation for C stubs (https://v2.ocaml.org/manual/intfc.html#s%3Ac-gc-harmony):
1. "A function that has parameters or local variables of type `value` must begin with a call to one of the `CAMLparam` macros and return with `CAMLreturn`, `CAMLreturn0`, or `CAMLreturnT`."
2. "Local variables of type `value` must be declared with one of the `CAMLlocal` macros. Arrays of values are declared with `CAMLlocalN`. These macros must be used at the beginning of the function, not in a nested block."
3. ...

Is this an oversight or is there some very good reason to not follow the rules?

Not doing so can lead to some very unusual GC bugs: https://github.com/xavierleroy/pringo/issues/6.

**Comment by michael-schwarz** [comment]
No, I think it was just an oversight.

**Comment by sim642** [comment]
It _might_ actually be fine because `caml_copy_double` is the only allocating operation in them. Accesses to all `value`-typed arguments happen before that, so GC won't move/delete anything we want to still access.

OCaml's own floating-point primitives also seem to be similar and not use the macros everywhere: https://github.com/ocaml/ocaml/blob/b2cd7e59e5b563b6a0527014689b7224bb678661/runtime/floats.c.
