### ISSUE TITLE
How to use Goblint for makefile-based C project?

### ISSUE THREAD

**Issue by kiligwither** [goblint/analyzer#158]
Dear developers:
       It may be a very trivial question but I couldn't find it at Readme. Thank you for your help.

**Comment by michael-schwarz** [comment]
Thanks for the question! You are right, we should add this to the README.

It should suffice to run Goblint with the Makefile as the file argument. Goblint will then automatically invoke `make` with the CC set to `cilly` which will generate a combined version of the program (so everything in one C file), that Goblint will then analyze.

If you get an error message that cilly was not found, add the bin directory of https://github.com/goblint/cil to your PATH.

I believe @jerhard has done this quite recently, so he should be able to help with any more problems that come up.

**Comment by kiligwither** [comment]
OK, thank you indeed!
