### ISSUE TITLE
Interval domain: Add wrap-around behavior 

### ISSUE THREAD

**Issue by jerhard** [goblint/analyzer#161]
## Goal
The interval domain should be improved by supporting wrap-arounds when possible, instead of going to `top` when a wrap around occurs.

For `unsigned` integer types, handling wrap-arounds precisely (when possible) should be the default (and only) behavior.
For `signed` integer types, the precise handling should only be activated when `ana.int.wrap_on_signed_overflow` is enabled. 

## Example
E.g., the interval domain should be able to handle something like the following pseudo code:

```
unsinged int x = MAX_INT; //MAX_INT for unsigned
int top;
if(top){
  x--;
} 
//[x -> [MAX_INT-1; MAX_INT]]
x = x + 2;
//[x -> [0; 1]

```

**Comment by michael-schwarz** [comment]
Is the plan here to then also add intervals `[a,b]` that are not normal in the sense that `a  <= b`?
I guess in most cases (except the one you constructed above where there is a must-overflow), the result of the operation will be such non-normal intervals.

**Comment by jerhard** [comment]
This is already implemented with setting the option `sem.int.signed_overflow` `assume_wraparound`.
