### ISSUE TITLE
Dubious dbg.timeout behavior

### ISSUE THREAD

**Issue by sim642** [goblint/analyzer#172]
I was running some benchmarks from [goblint/bench](https://github.com/goblint/bench) and noticed some running far longer than they should. The benchmark script there uses `--set dbg.timeout 900`, which I suppose should make Goblint time out after 900 seconds (15 minutes). On multiple occasions I saw no progress for a long time. When I looked at the `goblint` process in `htop` to kill it myself, I noticed it having used over 30 minutes of CPU time. The builtin timeout hadn't worked properly!

Looking at the code, there's some weird logic surrounding timeout:

1. Timeout is set (using SIGALRM, which I assume should work reliably) to call `Messages.waitWhat` after the given time:
https://github.com/goblint/analyzer/blob/956b9faaef2514cb530e6d9b8711106b3e3a6ab3/src/framework/control.ml#L514-L515
2. This function "stops the world" by raising `StopTheWorld` and also sets a boolean flag (to be sure?):
https://github.com/goblint/analyzer/blob/956b9faaef2514cb530e6d9b8711106b3e3a6ab3/src/util/messages.ml#L98-L103
3. It would all be great except transfer functions in `FromSpec` actually catch that exception and completely ignore the timeout having happened by evaluating to bottom:
https://github.com/goblint/analyzer/blob/956b9faaef2514cb530e6d9b8711106b3e3a6ab3/src/framework/constraints.ml#L691-L692
4. There is some extra logic in `common_ctx` of `FromSpec` that checks the boolean flag on every transfer function evaluation (why use the language's exception handling mechanism if we can just do it ourselves C-style, right?) and re-raises the exception:
https://github.com/goblint/analyzer/blob/956b9faaef2514cb530e6d9b8711106b3e3a6ab3/src/framework/constraints.ml#L530-L532

I see two issues with this:
1. When the timeout happens to occur exactly in the middle of transfer function evaluation, it gets ignored and everything continues running. I really don't understand why the exception is being caught there at all.
2. The re-raising in `common_ctx` appears as if it's there to work around the first issue, but it's completely broken: since `common_ctx` is called within `tf`. The exception it re-raises gets caught and ignored by the same handler. So not only does the analysis continue running after timeout, it can also make no progress and gets stuck in a loop, because the boolean flag causes the exception to be re-raised and ignored every time the solver evaluates a transfer function.

I would gladly just rip all the world-stopping logic out of `FromSpec` because I can't see any use to it and it just breaks timeout. But that code must've been added at some point for some reason, so maybe there was a reason for it working in this convoluted way and just got broken by later changes?

**Comment by vesalvojdani** [comment]
I don't know what was being attempted. I don't think I introduced this StopTheWorld business. Maybe someone wanted already computed parts to be output. I suspected that this StopTheWorld was part of the interactive solver, but it does not seem to rely on this mechanism.

**Comment by vogler** [comment]
I was also confused by this StopTheWorld at one point. I also assumed the idea was to let the solver finish but with every tf returning bot.

> So not only does the analysis continue running after timeout, it can also make no progress and gets stuck in a loop, because the boolean flag causes the exception to be re-raised and ignored every time the solver evaluates a transfer function.

At least looking at those snippets, you'd think it should work and just return bot. Where's the re-raise loop?

**Comment by sim642** [comment]
Well yes, it does return bottom for that evaluation, but spending 15+ minutes after the timeout just evaluating everything to bottom doesn't seem right either.

The reasonable thing to do would be to move the timeout handling out of the analysis specification and make it actually terminate after the timeout, as opposed to continuing doing who knows what for who knows how long. I think having a reliable and unsurprising timeout feature would be preferable to letting the solver (hopefully) finish and return a beginning of a solution, which I don't know if anyone has actually used.

**Comment by vogler** [comment]
Good points. Idk if there is some use for the bot solution, maybe comparing precision, but that also wouldn't work as is since there is no difference between 'stopped' and 'determined dead code'?

**Comment by michael-schwarz** [comment]
I would also be in favor of removal as Simmo suggested!
