### ISSUE TITLE
missing write to argument in recursion

### ISSUE THREAD

**Issue by vogler** [goblint/analyzer#173]
The write to `a` in the second call to `rec2` is missing in the result.

https://github.com/goblint/analyzer/commit/78bec7121cab66b0f84b5532b51c9f0f30a6d8a7

https://github.com/goblint/analyzer/blob/78bec7121cab66b0f84b5532b51c9f0f30a6d8a7/tests/regression/01-cpa/05-recursion.c#L43

**Comment by vogler** [comment]
Oops, missed the order of rec. call and assignment. So, it works as expected.

**Comment by michael-schwarz** [comment]
The test is still strange. It asserts `a==9` which can never happen.
I now fixed the assert and removed the `SKIP!` annotation

**Comment by vogler** [comment]
Yes, I was confused by the assert, that's why I assumed the order to be different.
