### ISSUE TITLE
Error happening when analyzing a makefile project

### ISSUE THREAD

**Issue by ycaibb** [goblint/analyzer#181]
Hi, developers.

I used the command `goblint Makefile` to analyze a project `bzip2smp`. It shows the error below. What should I do? Thank you for helping.

```
Cannot start GNUCC at /home/rando/.opam/4.06.0/bin/../lib/perl5/App/Cilly.pm line 2212.
make: *** [bzip2smp.o] Error 2
cilly --gcc=/usr/bin/gcc-6 --merge --keepmerged -gstabs -W -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_REENTRANT -D_GNU_SOURCE  -o bzip2smp.o -c bzip2smp.c
Makefile:8: recipe for target 'bzip2smp.o' failed
Fatal error: exception Failure("Failed combining files. Make terminated with exit code 2.")
```

**Comment by jerhard** [comment]
When running Goblint on a Makefile, Goblint needs to know the location of the GCC-binary on your system.
By default, Goblint is using `/usr/bin/gcc-6` as the path to your gcc installation. 

You can give the path to the GCC-binary to Goblint via the `exp.gcc_path` flag. E.g.:
```
./goblint /path/to/project/Makefile --set exp.gcc_path "'/usr/bin/gcc'"
```

**Comment by ycaibb** [comment]
Thank you for the answer! I still got this error.  What's the reason?

```
Download.c:33: Error: Incompatible declaration for bwritten (from Download.o(5)).
 Previous was at Signal.c:16 (from Signal.o (4)) (different integer types int  and unsigned int )
Resume.c:15: Error: Incompatible declaration for bwritten (from Resume.o(6)).
 Previous was at Download.c:33 (from Download.o (5)) (different integer types unsigned int  and int )
Download.c:33: Warning: The name bwritten is used for two distinct globals
Error: There were errors during merging
Fatal error: exception Errormsg.Error
make: *** [all] Error 2
cilly --gcc=/usr/bin/gcc-5 --merge --keepmerged -g -W   -c -o main.o main.c
cilly --gcc=/usr/bin/gcc-5 --merge --keepmerged -g -W   -c -o Aget.o Aget.c
cilly --gcc=/usr/bin/gcc-5 --merge --keepmerged -g -W   -c -o Misc.o Misc.c
cilly --gcc=/usr/bin/gcc-5 --merge --keepmerged -g -W   -c -o Head.o Head.c
cilly --gcc=/usr/bin/gcc-5 --merge --keepmerged -g -W   -c -o Signal.o Signal.c
cilly --gcc=/usr/bin/gcc-5 --merge --keepmerged -g -W   -c -o Download.o Download.c
cilly --gcc=/usr/bin/gcc-5 --merge --keepmerged -g -W   -c -o Resume.o Resume.c
cilly --gcc=/usr/bin/gcc-5 --merge --keepmerged -o aget main.o Aget.o Misc.o Head.o Signal.o Download.o Resume.o -pthread
Makefile:11: recipe for target 'all' failed
Fatal error: exception Failure("Failed combining files. Make terminated with exit code 2.")
```

**Comment by vogler** [comment]
@jerhard Does it need to be gcc 6 (current version is 10)? If not, the right binary could be detected like `Config.cpp`. cilly needs gcc instead of cpp?

@ycaibb The declarations have to match. Can you fix it by e.g. changing both to `unsigned int`?

**Comment by ycaibb** [comment]
@vogler Thank you. It runs.

**Comment by michael-schwarz** [comment]
@ycaibb:  If you have any more questions, feel free to open a new issue or reopen this one!

**Comment by vogler** [comment]
@ycaibb Also beware that you might have changed the semantics of the program by unifying the declarations. The linker just trusts the declaration. It looks like `bwritten` should return `unsigned int` but you need to check that there's nothing that (erroneously or not) relies on `int` semantics (e.g. signedness) where it was declared like that (in this case unlikely, but just a general advice).

**Comment by ycaibb** [comment]
@vogler and @michael-schwarz  Thank you!
