### ISSUE TITLE
Remove toXML_f and toXML

### ISSUE THREAD

**Issue by vogler** [goblint/analyzer#20]
For XML output `printXML` is used instead of `toXML` because `toXML` was too slow/memory intensive for large outputs.
The problem with removing it, is that it is used for `result` options `indented`, `compact`, `html`.

**Comment by vesalvojdani** [comment]
I would really like to see this happen, but we still occasionally use result html. What is the state of the g2html tool?

**Comment by vogler** [comment]
Why/what do we still use it for? The g2html output should have the same/more functionality.
Ideally #31 should get rid of all these output/printing functions.

**Comment by vesalvojdani** [comment]
I will try the g2html tool on some of the larger benchmarks, but I think we should move forward with only the new html generation and start aggressively deleting legacy code and other redundancies.

**Comment by jerhard** [comment]
What is the status on this? Is there a reason to keep these functions or not?

**Comment by michael-schwarz** [comment]
Are these the ones used for `--sets result html`? I still occasionally use
that.

**Comment by jerhard** [comment]
>Are these the ones used for `--sets result html`?
Yes. If it's still used we should think about whether we want to keep this issue open, I guees?

**Comment by michael-schwarz** [comment]
It doesn't seem like the `--sets result html` has too many things that `--html` doesn't. Ralf and I made a list of these things at some point:

- Its highlighting of dead-code is a bit more intuitive then in thew new output,
- It layouts contexts and the results for them better [(context, path)] vs two separate lists: {context: [context], path: [path])
- Has a list of clickable warnings

But maybe we should move forward and remove `--sets result html` as having to different ways of creating XML is something that's rather strange.

What's everyone else's take on this?
