### ISSUE TITLE
Serialization and incremental runs fail with `--disable ana.opt.hashcons`

### ISSUE THREAD

**Issue by keremc** [goblint/analyzer#228]
The use of `Lazy.t` in [`HashCached`](https://github.com/goblint/analyzer/blob/25f8eb4eb39438e3bee23618d8a9724d1a320069/src/domains/printable.ml#L174) causes objects of type `HashCached.t` to be unserializable unless the lazy value has been computed already. Presumably, `Lazy.t` is implemented as something like `type 'a t = Ready of 'a | Not_ready of (unit -> 'a)`, and the serialization fails when it encounters the second variant. By default, hash consing causes all hash values to be computed, but with `--disable ana.opt.hashcons`, hashes are left uncomputed, and serialization fails.

Possible solutions:
* @michael-schwarz suggested iterating over all entries in the result tables `lh` & `gh` and computing the hash values anyway when hash consing is disabled and `save_run` is specified
* Another way is to replace `Lazy.t` with a mutable field of `option` type

Note: Js_of_ocaml doesn't support [`Marshal.Closures`](https://ocaml.org/api/Marshal.html#VALto_channel), which is why I didn't list it as an option.

Example:
```
kerem@desktop:~/repos/analyzer$ ./goblint tests/regression/00-sanity/01-assert.c --sets save_run run
runtime: 00:00:00.037
vars: 11, evals: 13
[...]
Memory statistics: total=10.59MB, max=4.39MB, minor=8.88MB, major=3.54MB, promoted=1.83MB
    minor collections=4  major collections=1 compactions=0
kerem@desktop:~/repos/analyzer$ ./goblint tests/regression/00-sanity/01-assert.c --sets save_run run --disable ana.opt.hashcons
About to crash! (initfun:0)

runtime: 00:00:00.029
vars: 11, evals: 13
[...]
Fatal error: exception Invalid_argument("output_value: functional value")
```

**Comment by sim642** [comment]
> Presumably, `Lazy.t` is implemented as something like `type 'a t = Ready of 'a | Not_ready of (unit -> 'a)`, and the serialization fails when it encounters the second variant.

It's actually even worse than that. Laziness is built into the OCaml compiler itself and some things are done via `Obj` magic: https://github.com/ocaml/ocaml/blob/9ffd97f3eec0c45ead5e395a298b4a4a54fe26c1/stdlib/lazy.ml#L50-L56.


>    Another way is to replace `Lazy.t` with a mutable field of `option` type

This sounds like a reasonable way to go about it. Because the lazily evaluated function `hash` is fixed, there's no need for closures indeed.
