### ISSUE TITLE
wrong priorities of globals

### ISSUE THREAD

**Issue by vogler** [goblint/analyzer#27]
Privatization is a complicated and not well documented feature with strange effects.
In particular it seems to query globals before side-effects to them are generated? This causes non-termination for interval analysis on globals with the slr3 solver.

    ./goblint --enable ana.int.i⇡terval --sets solver slr3 tests/regression/04-mutex/01-simple_rc.c

**Comment by vesalvojdani** [comment]
I'm looking into this now. I can't reproduce the non-termination issue. Have you changed something meanwhile?

**Comment by vesalvojdani** [comment]
Okay, the real culprit is [this line](https://github.com/goblint/analyzer/blob/79133a54cd6b033ea1e7a68d694d2e677c2c4c86/src/analyses/mutex.ml#L579) in mutex.ml. I'm thinking about what the proper fix should be.
