### ISSUE TITLE
Refactor CIL helper mappings to be consistent

### ISSUE THREAD

**Issue by sim642** [goblint/analyzer#290]
_Originally posted by @sim642 in https://github.com/goblint/analyzer/pull/274#discussion_r670213389_

We have a bunch of helper mappings for CIL stuff that are defined and populated all over the place inconsistently:
- [x] `MyCFG.getFun` looks up for `node` the `fundec` it's in.
- [x] `Cilfacade.getFun` looks up for `string` the `fundec` with that name.
- [x] `Cilfacade.getdec` looks up for `varinfo` the `fundec` with that as function variable.
- [x] `InvariantCil.var_find_fundec` looks up for `varinfo` the `fundec` it's declared in (as local or formal).
- [x] `InvariantCil.var_find_original_name` looks up for `varinfo` the `string` containing its original name in the input file (before CIL renamed it).

And possibly something else I currently forgot.

These should be organized to one clear place and constructed in consistent manner instead of being intertwined with CFG construction or each one doing a separate `Cil.iterGlobals` (or even worse, doing that on each lookup without storing a mapping).

**Comment by sim642** [comment]
@jerhard This commit adds a copy of `MyCFG.getLoc` as `Tracing.getLoc` which has an extra ability to override locations of nodes. `Tracing.getLoc` is only used in one place, everywhere else `MyCFG.getLoc` is still used, which still has the un-overridden locations.

Is there a reason for that? Seems to me like it'd be better (and consistently fix the locations in other places not just the result output) if there was just `MyCFG.getLoc` which always does this override lookup and `Tracing.getLoc` wouldn't be necessary.

Additionally, I might be able to use this location override mechanism to fix #292 by giving it a location.

**Comment by jerhard** [comment]
>Is there a reason for that?

For the incremental analysis, one needs to override the mapping of nodes to locations that is used when generating warnings. The reason for this is that nodes in functions that have not been changed might still be in a different location now, so the warnings should reflect the new location. 
However, during the analysis, we rely on the location to generate new `varid`s, e.g. for the memory blocks allocated by `malloc`. This means that if one were to reanalyze code in unchanged functions, it would lead to the creation of different `varid`s for these `malloc`ed blocks, if one were to change the locations of the nodes that is available during the analysis.

**Comment by sim642** [comment]
> This means that if one were to reanalyze code in unchanged functions, it would lead to the creation of different `varid`s for these `malloc`ed blocks, if one were to change the locations of the nodes that is available during the analysis.

But unchanged functions aren't reanalyzed, or? Because if they aren't, then their results wouldn't change and would still contain `alloc@` variables with the old line numbers.

Also, what happens if the a new function is inserted such that it contains a `malloc` on exactly the same line as an unchanged function which previously had a `malloc` on that line? Then the two `alloc@` variables are the same (and in some case possibly joined) whereas if the new program were to be analyzed from scratch, they would have different locations and not be considered the same.

**Comment by jerhard** [comment]
>But unchanged functions aren't reanalyzed, or?

Parts of them might be reanalyzed when some of the functions they called have changed. 

>Then the two alloc@ variables are the same (and in some case possibly joined) whereas if the new program were to be analyzed from scratch, they would have different locations and not be considered the same.

yes, that might happen. The cleaner solution with regards to incremental analysis would be, that the generated `varid`s (e.g. in the `MallocWrapperAnalysis`) don't depend on the node's location, but its `id`.

**Comment by sim642** [comment]
> Parts of them might be reanalyzed when some of the functions they called have changed.

If the reanalyzed part is after the `malloc`, then it won't matter because the `malloc` isn't reanalyzed. If the reanalyzed part is before the `malloc`, then it would reanalyze the rest of the function anyway, so it doesn't matter which location it's using since every use of it gets reanalyzed.


> yes, that might happen. The cleaner solution with regards to incremental analysis would be that the generated `varid`s (e.g. in the `MallocWrapperAnalysis`) don't depend on the node's location, but its `id`.

Not sure how that would even work because currently the supposedly fresh `vid` (which we don't actually check if it's fresh...) depends on the hash of the `varinfo`, which depends on the `vname`, which contains the location. If the location isn't there, they would all have the same `vid`. And you cannot have the `vid` in the name because the `vid` is calculated based on the name (among other things), so it's completely circular.

If a proper fresh `varinfo` mechanism is implemented, it would be able to just give out fresh `vid`s one by one, but then you have plenty of more problems:
1. It depends on the order of evaluation in the solver etc.
2. Reanalysis of the same transfer in the same context (without incrementality) would even give a new `varinfo` instead of the same one each time, so no fixpoint is even possible!

The current location-based naming doesn't have either of these issues.

**Comment by jerhard** [comment]
>If the reanalyzed part is before the malloc, then it would reanalyze the rest of the function anyway, so it doesn't matter which location it's using since every use of it gets reanalyzed.

At widening points, the incremental analysis might join abstract values from the old run with those computed for the current right-hand-side. This could possibly lead to the case where there are multiple representations for the same allocated block in the abstract state.

> And you cannot have the vid in the name because the vid is calculated based on the name (among other things), so it's completely circular.

It would be the `id` of the current node instead of the location of the current node as it is now.

**Comment by sim642** [comment]
> It would be the `id` of the current node instead of the location of the current node as it is now.

Ahh the `sid` for `Statement` nodes, that makes more sense. Although there's a bit of ambiguity with that because the allocating happens on a transfer function from `ctx.prev_node` to `ctx.node`, which one would it use? `ctx.node` sounds more like the "current" node, although it actually means the future node that's currently being evaluated. So it seems a bit weird that the allocation is identified by what comes after the allocation transfer. Also the join of two branches which both end in allocation get the same ID in the `varinfo`, although they happen at different locations (which are currently distinguished by the different locations of those statements).

`ctx.prev_node` would then seem more appropriate, but I'm not completely sure of it either because I added that just for witness generation and it's used for nothing else AFAIK.

I guess doing it with statement IDs would then eliminate the need for keeping `MyCFG.getLoc` which returns the un-overridden locations and `Tracing.getLoc` could completely replace it?
It's still worrying though because then nothing can really depend on locations if we want incremental to work right. So thread IDs would also need to be changed similarly and possibly something else. It seems more robust indeed, although less user-friendly because then you cannot immediately know the location of allocation/thread creation.
