### ISSUE TITLE
Unsoundness of modulo operations involving negative numbers

### ISSUE THREAD

**Issue by michael-schwarz** [goblint/analyzer#301]
Most of our domains seem to be unsound w.r.t. modulo operations involving negative numbers:

~~~C
#include "assert.h"
int main() {
    int x = -1;
    int z = x % 5;
    assert(z == -1);
}
~~~
For GCC and Clang the value of `z` is `-1`. Our domains have for `z` :
- `4` for `DefExc` 
- `bottom` for Interval. 

C99 Standard: http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1124.pdf
> If the quotient a/b is representable, the expression (a/b)*b + a%b shall equal a.

If we set `b=5` and `x=a=-1`, also according to the standard `z` needs to be -1.

**Comment by michael-schwarz** [comment]
The cause seems to be that `Big_int` (and `Big_int_Z`) provide the actual mathematical modulo operation while we need the remainder operation which Ocaml helpfully calls `mod` instead.

**Comment by sim642** [comment]
This is the case where `a` in `a % b` is negative, but what about when `b` is negative (or both)? Is that all covered by this?

Because I remember some of the negative cases of modulo being implementation-defined, but quick googling says that might've been before C99, while C99 guarantees the quoted behavior.

**Comment by michael-schwarz** [comment]
> This is the case where a in a % b is negative, but what about when b is negative (or both)? Is that all covered by this?

Yes, I tested all of them: https://github.com/goblint/analyzer/pull/302/files#diff-e3c7aaa895e9f17c3fcf7848aa73329e33c491a3b24c1918f47c597587247ed9


> Because I remember some of the negative cases of modulo being implementation-defined, but quick googling says that might've been before C99, while C99 guarantees the quoted behavior.

Yes, in C90 it indeed is implementation defined.

**C90**
>   When integers are divided and the division is inexact, if both operands are positive the result of the / operator is the largest
integer less than the algebraic quotient and the result of the % operator is positive.  **If either operand is negative, whether the
result of the / operator is the largest integer less than the algebraic quotient or the smallest integer greater than the algebraic quotient is implementation-defined, as is the sign of the result of the % operator.**

**C99**
>When integers are divided, the result of the / operator is the algebraic quotient with any fractional part discarded.88)

Both standards however still mandate
>  If the quotient a/b is representable, the expression (a/b)*b + a%b shall equal a .

**So, a C90 conforming implementation might indeed have `-1%5==4` but then it would also have `-1/5==-1`.
But I think this is mostly besides the point.**
