### ISSUE TITLE
More excessive and missing Neg(1) edges in CFG

### ISSUE THREAD

**Issue by sim642** [goblint/analyzer#306]
### Example
https://github.com/goblint/analyzer/blob/0e6698e178e9b33ace993e2cb8ed4b93c160bdb1/tests/regression/34-localization/02-hybrid.c#L8-L17

After #305 it would have the following CFG:
![image](https://user-images.githubusercontent.com/378740/126952878-a5489f3d-72f5-48f5-8202-f2422f4e56fb.png)

**Problem:** there's an unnecessary Neg(1) edge 11 → 18.

### Problem
Initially no Neg(1) edges are inserted, but we simply record at each loop where the Neg(1) edge would go. So we have candidates 6 → 22 and 11 → 18.
Then a backwards graph traversal from the function return node just reaches node 22 and nothing else. This reveals that both loops are not connected.
Then _all_ the Neg(1) candidates are added and the CFG becomes connected. However one of them was excessive.

### Solution ideas
One might imagine inserting the candidates one by one and rechecking connectedness each time. So insert 6 → 22 and find out that everything is now connected. Thus 11 → 18 wouldn't be added.
Unfortunately this relies on non-determinism, because just as easily 11 → 18 might be inserted first. Then the CFG still isn't connected and 6 → 22 is added as well. The CFG is now connected but still contains the excessive edge.

So somehow we want a minimum subset of the candidates which ensures connectedness. Considering that the insertion of one candidate may affect the connectivity is all sorts of ways, I'm not even sure there's a neat non-exhaustive way of doing that.

I also doubt it's possible to solve this greedily by just ordering the candidates in some particular way because x < y could both mean y comes after x sequentially or y is inside the nested loop of x. And that's all assuming CIL numbers them in any reasonable way to begin with. Moreover, we need to be able to handle arbitrarily intricate goto loops, which aren't `Loop`s in CIL sense at all.

All this sounds like we need some fairly sophisticated graph algorithms. Like detecting strongly connected components (SCC) which correspond to loops (explicit or goto) and then topologically sorting the component graph to find out which loops come after which loops, so it's possible to just add the Neg(1) edge from the last loop. This SCC loop detection should also help with #233 because then one can identify all the edges entering a loop.

### Unconnectedness problems
All the above discussion was about avoiding some excessive Neg(1) edges, but I tried out all combinations of sequencing, branching and nesting of finite and infinite loops and found out that there are cases where even the current excessive-edges implementation doesn't connect the CFG.

For example these silly programs:
```c
  while (1)
    assert(1);

  while (1)
    assert(1);
```
```c
  while (1)
  {
    while (1)
      assert(1);
  }
```
The first case has a problem where the second loop head isn't detected because it's loop head finding (which starts from the entry node) doesn't even reach it without Neg(1) added first.
The second case has a problem where I think the loop heads coincide, so only Neg(1) edge is added while two are necessary for two infinite loops.

Rethinking the whole Neg(1) insertion logic thus needs to also fix these cases. Or we should just crash with the "low quality code" warning...

**Comment by michael-schwarz** [comment]
With SV-COMP on the current master, there seem to also be `~1000` programs where the exit is not connected to the start
`MyCFG.createCFG: FunctionEntry not connected to Function (return)`. It seems to be mostly LDV benchmarks.

[master-unconnected.zip](https://github.com/goblint/analyzer/files/6912665/master-unconnected.zip)

**Comment by sim642** [comment]
> With SV-COMP on the current master, there seem to also be `~1000` programs where the exit is not connected to the start
> `MyCFG.createCFG: FunctionEntry not connected to Function (return)`. It seems to be mostly LDV benchmarks.

Looking at the first failure in the list, I found the incredibly silly problem in this unused LDV function:
```c
void ldv_module_put_and_exit(void)
{
  {
  {
  ldv_module_put((struct module *)1);
  }
  LDV_STOP: ;
  goto LDV_STOP;
}
}
```

Seems weird because this empty goto loop works just fine in our tests:
https://github.com/goblint/analyzer/blob/d9c4818ad7c8993170d953b8881f4294a47716e2/tests/regression/00-sanity/21-empty-loops.c#L30-L34

Turns out that the semicolon between the label and the goto makes a difference to CIL... Instead of a single `Goto` statement having itself as successor, it now has a `Block` containing a `Goto` statement and there's a mutual successor loop between them.

**Comment by sim642** [comment]
I fixed this directly onto master by also handling the special case for empty `Block`s. For the SCC stuff I'll still open a PR since that's a bigger change.
