### ISSUE TITLE
5306 programs fail with `texpr1_expr_of_cil_exp` with octApron and MutexMeet privatization

### ISSUE THREAD

**Issue by michael-schwarz** [goblint/analyzer#317]
When running SV-Comp on the current master with octApron enabled (everything else default settings), around 5000 programs fail with `Fatal error: exception Failure("texpr1_expr_of_cil_exp: globals must be replaced with temporary locals")`.

The most simple example program that fails that I could extract is this one:

~~~C
// SKIP PARAM: --sets ana.activated[+] octApron --enable ana.int.interval
int ARR_SIZE ;

int main() {
    int count = 0;
    while(count<ARR_SIZE) {
        count++;
    }
    return 0 ;
}
~~~

[List of all failing programs](https://github.com/goblint/analyzer/files/6953852/failing.txt)

**Comment by sim642** [comment]
I haven't looked at the code but I suspect the issue might be something as simple as one of the following:

- [ ] Temporary locals not being introduced while still in single threaded mode.
- [ ] Temporary locals not being introduced in `branch`.

I wouldn't even be surprised if there's some TODO in the code.
