### ISSUE TITLE
Sync for branched thread creation should also consistently publish to initial values like `enter_multithreaded`

### ISSUE THREAD

**Issue by sim642** [goblint/analyzer#327]
At https://github.com/goblint/analyzer/pull/321#discussion_r686565112 it turned out that `sync Join` for other privatizations (including in base) should also publish to initial values just like `enter_multithreaded` would.

For example, we're unsound in the following example:
```c
// SKIP PARAM: --enable ana.int.interval
#include <pthread.h>
#include <assert.h>

int g = 1;
pthread_mutex_t A = PTHREAD_MUTEX_INITIALIZER;

void *t_fun(void *arg) {
  return NULL;
}

int main(void) {
  int x, r;
  pthread_t id;

  if (r) {
    pthread_create(&id, NULL, t_fun, NULL);

    pthread_mutex_lock(&A);
    g = 5;
    pthread_mutex_unlock(&A);
  }
  else {
    g = 10;
  }

  pthread_mutex_lock(&A);
  x = g; // may read 10!
  pthread_mutex_unlock(&A);
  return 0;
}
```

Alternatively making threadflag path-sensitive should avoid all such cases and keep single- and multithreaded mode separate. Then no `sync Join` should be necessary.

**Comment by michael-schwarz** [comment]
An alternative fix might be enhancing our MT domain to not have `ST \leq MT` but instead have them incomparable and redo the publishing whenever we definitely go multithreaded from `ST \sqcup MT`.
This requires also always reading the local copies of globals and never removing from the local state.

**Comment by michael-schwarz** [comment]
What is the relationship of this issue and #487? Is it fixed now?

**Comment by sim642** [comment]
I think so. I had completely forgotten about this issue. I'll add this example as well and check it. If this it's fixed I'll just close this issue.
