### ISSUE TITLE
Rename octApron -> apron, remove poly

### ISSUE THREAD

**Issue by sim642** [goblint/analyzer#329]
The octApron analysis is a thoroughly fixed and improved copy of the old poly analysis, which can now be considered deprecated. Although the name of octApron refers to octagons, it can be changed to use any domain from Apron, so it'd be appropriate to rename it to avoid possible confusion.

Since the rename would touch all octApron files, it's best done after the following are merged, to avoid possible conflicts:
* #324 
* #328
* #322

**Comment by michael-schwarz** [comment]
While doing this, we might also wonder if we want to keep the original `octagon` analysis that was added by a student, or whether it should be retired in favor of Apron.
I guess to answer this, one would have to benchmark both on larger programs.

**Comment by sim642** [comment]
I think we can keep the octagon analysis for the time being and leave its removal to whenever we plan to do a more thorough cleanup of outdated analyses.

Functionality-wise octApron should cover octagon, at least octApron regression tests include the octagon ones. Performance-wise I'd guess octApron is faster because it's Apron, which is written in C and not by a student, but of course we can also benchmark it at some point.
