### ISSUE TITLE
Set default values or document how to run g2html

### ISSUE THREAD

**Issue by vesalvojdani** [goblint/analyzer#35]
It is difficult to get the g2html tool to run. It would be nice to run it with just `--enable g2html`. The deafault location for the jar should be g2html/g2html.jar, but I'm not sure what other params I need to feed the analyzer.

**Comment by vogler** [comment]
`--html` does this. `make jar` to build, followed by `./goblint --html ...`, then open `result/index.xml`.

Changing the default location from from `g2html.jar` to `g2html/g2html.jar` has the disadvantage that you can't just copy it and later clone the submodule:

    git submodule update --init --recursive g2html
    fatal: destination path 'g2html' already exists and is not an empty directory.
    fatal: clone of 'https://github.com/goblint/g2html.git' into submodule path 'g2html' failed

On the other hand `make jar` could delete it first.

**Comment by vesalvojdani** [comment]
Ah, yes, I forgot there is the make jar in the goblint build script... Seems g2html is actually documented on the main readme. Not sure how I could miss it.

**Comment by vesalvojdani** [comment]
Okay, everything works as it should...
