### ISSUE TITLE
better detection and reporting of runtime errors

### ISSUE THREAD

**Issue by vogler** [goblint/analyzer#36]
Examples:
- array index out of bounds
- segfaults: null-pointer access, ...?
- div by zero
- memory leaks
- undefined behavior (see [ubsan](http://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html))
- wrong API usage (use automatons)

Each warning should have tags/a category to be able to filter runtime errors/soundness warnings/assumptions etc.

**Comment by vogler** [comment]
related: #55

**Comment by vesalvojdani** [comment]
What is the actual status of this? Is there currently some easy way to just run goblint and see assertion failures without running in debug mode? Hmm... maybe this task and issue #55 should receive a bump in prioritization!

**Comment by vogler** [comment]
No, IMO `dbg.debug` should be the default. There's https://github.com/goblint/analyzer/pull/68 which extends runtime error detection and has some basic implementation for #55.

@keremc What's up with the wrong references? I assume those are issues in the respective other projects that github shows as ours. What did you do to include their commits? Can't you use an opam pacakge or git submodule (or sqash commits)?

**Comment by sim642** [comment]
> No, IMO `dbg.debug` should be the default.

I kind of agree with this. There are very important warnings (like undefined functions, unknown function pointers, invalidation of all globals) that indicate total loss of precision but are completely hidden by default. And in #183 I added some more around those, to definitely see those things having happened instead of spending hours trying to figure out why everything is top.

But as is, `dbg.debug` output has also lots of stuff which is hard to interpret without looking into Goblint source code and maybe even tracing to figure out why some stuff is triggered at all in the first place. Definitely not user-friendly.

> There's #68 which extends runtime error detection and has some basic implementation for #55.

I didn't investigate #68 deeply, but it didn't look too much, so I'm not sure if it's worth fishing that part out of there. Might be easier to just design a warning system from scratch into the current state of Goblint.

> @keremc What's up with the wrong references? I assume those are issues in the respective other projects that github shows as ours. What did you do to include their commits? Can't you use an opam pacakge or git submodule (or sqash commits)?

I think they forked Goblint but then force pushed some totally other project's code into their fork...

**Comment by keremc** [comment]
@vogler I was using Git subtrees to include a modified version of Zarith in my personal fork of Goblint. Unfortunately, it ended up creating some frivolous references in this issue tracker.

**Comment by vogler** [comment]
@keremc Ok, need to remember that they don't play well with github. Can you easily split it out into a fork of zarith with `git filter-branch`?
https://docs.github.com/en/github/getting-started-with-github/splitting-a-subfolder-out-into-a-new-repository

**Comment by keremc** [comment]
@vogler I can but I don't think it will remove the [references that already exist](https://github.com/isaacs/github/issues/1235). In the future, I will definitely prefer fork + submodules over subtrees.

**Comment by vogler** [comment]
> There are very important warnings (like undefined functions, unknown function pointers, invalidation of all globals) that indicate total loss of precision but are completely hidden by default. And in #183 I added some more around those, to definitely see those things having happened instead of spending hours trying to figure out why everything is top.
> 
> But as is, `dbg.debug` output has also lots of stuff which is hard to interpret without looking into Goblint source code and maybe even tracing to figure out why some stuff is triggered at all in the first place. Definitely not user-friendly.

True. Requires sane defaults, cleanup and some prios/colors to indicate what impact a message has.
At some point I thought about
- listing the assumptions goblint made regarding precision vs. soundness  as a group at the end of the output
- some guided/interactive mode that asks the user before applying these 'nuclear' options if they come up

OTOH (student) work might be better spent on making the non-terminal output more user-friendly.

Re. finding out where precision was lost, one could also think about tracking loss in some analysis (random value top vs. join/widen top etc.) or (very hypothetical) making options part of the constraint system to allow for partial re-solving (incremental td3).

> I didn't investigate #68 deeply, but it didn't look too much, so I'm not sure if it's worth fishing that part out of there. Might be easier to just design a warning system from scratch into the current state of Goblint.

Yes, I think I didn't merge it because I thought the same about those message pools.
(It's not very inter-connected. The spec extensions look useful, but if no one is using it, there's no need to merge it. OTOH maybe it should be used more - at least concerning the last point 'wrong API usage (use automatons)'.)

**Comment by michael-schwarz** [comment]
Closing in favor of opening individual issues.
