### ISSUE TITLE
Locations in thread IDs cause incremental inconsistencies

### ISSUE THREAD

**Issue by sim642** [goblint/analyzer#374]
In #356 the `varinfo`s for `malloc`-ed variables were changed not to contain locations because over incremental runs, code might shift and the reused `varinfo`s would be different from when they'd be analyzed from scratch. Therefore they were adjusted to be based on nodes instead.

As noted in https://github.com/goblint/analyzer/pull/356#pullrequestreview-760887387 and https://github.com/goblint/analyzer/pull/369#discussion_r723459577, the same problem is possible with thread IDs if the thread creation's line shifts around.

**Comment by jerhard** [comment]
We should do the same thing as for the `MallocWrapperAnalysis`, i.e. creating the `varinfo`s based on the `sid` of an associated node. The `show` function of `BaseType.Variables` would also have a special handling for threadIds then, taking the line number of the associated node from some hashtable.

I think it makes sense to have one singular hashtable for these location based and dynamically created `varinfo`s, so this `BaseType.Variables.show` has to only check whether something is a location based var, and add the line number of the associated node then.

**Comment by jerhard** [comment]
@sim642 As far as I see, there is currently no mechanism to serialize `RichVarinfo` Hastables, as used in `ThreadIdDomain`, right?

**Comment by sim642** [comment]
> I think it makes sense to have one singular hashtable for these location based and dynamically created `varinfo`s, so this `BaseType.Variables.show` has to only check whether something is a location based var, and add the line number of the associated node then.

Yes, it should be generic in that sense.

> As far as I see, there is currently no mechanism to serialize `RichVarinfo` hashtables, right? E.g. the one used in `ThreadIdDomain` are not serialized?

No, the need for this wasn't yet known when I designed the `RichVarinfo` API to make its internal hashtable as transparent as possible. It would probably have to be redesigned to not return just a wrapper function, but also a reference to the inner hashtable if one wants to marshal it. For unmarshaling one needs a way to construct the wrapper function from a pre-existing hashtable.

When we fixed mallocWrapper, I realized it's doing something very similar to `RichVarinfo`, but with the difference, that it does an extra thing only for each _new_ `varinfo` it creates. Currently `RichVarinfo` doesn't have a way of hooking into it like that, but if it's redesigned, it's probably good to think of that at the same time as well.

**Comment by jerhard** [comment]
>As noted in #356 (review) and #369 (comment), the same problem is possible with thread IDs if the thread creation's line shifts around.

@stilscher Is there an example where this is or was a problem for thread-Ids or Mallocs? At least in the current `master`, statements in functions that are detected as unchanged are set back to the old, previously stored nodes, including the `location`.
https://github.com/goblint/analyzer/blob/9d1d18961fd393496e0d264c9046a8f7216b09e8/src/incremental/updateCil.ml#L50-L63
