### ISSUE TITLE
Unsoundnesses in SV-COMP 2022

### ISSUE THREAD

**Issue by sim642** [goblint/analyzer#382]
SV-COMP 2022 prerun results for the Goblint archive from SV-COMP 2021, but with updated sv-benchmarks, reveals unsoundness in three benchmarks:
- [ ] busybox-1.22.0/cut-3
- [ ] busybox-1.22.0/expand-2
- [ ] busybox-1.22.0/wc-2

These tasks were not used for ReachSafety last year because they were accidentally missing from a `.set` file: https://gitlab.com/sosy-lab/benchmarking/sv-benchmarks/-/merge_requests/1306. This is why the unsoundness didn't show in SV-COMP 2021 final results.

I just checked that the unsoundness is still present on https://github.com/goblint/analyzer/commit/d4d9ace1fafbf01beac29e909460ef9ecad04115.

---

Additionally, the following issues were uncovered with the old set of benchmarks, and the updated Goblint:

- [x] ldv-linux-3.0/module_get_put-drivers-block-drbd-drbd.ko.cil.out-2.yml
- [x] ldv-linux-3.0/module_get_put-drivers-usb-core-usbcore.ko.cil.out.yml
- [x] ldv-linux-3.0/usb_urb-drivers-media-dvb-ttusb-dec-ttusb_dec.ko.cil.out.yml
- [x] ldv-linux-3.0/usb_urb-drivers-staging-lirc-lirc_imon.ko.cil.out.yml
- [x] ldv-linux-3.4-simple/32_7_cilled_const_ok_linux-32_1-drivers--input--mouse--synaptics_usb.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.yml
- [x] ldv-linux-3.4-simple/32_7_cilled_const_ok_linux-32_1-drivers--mtd--chips--cfi_cmdset_0001.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.yml
- [x] ldv-linux-3.4-simple/32_7_cilled_const_ok_linux-32_1-drivers--net--wireless--p54--p54usb.ko-ldv_main0_sequence_infinite_withcheck_stateful.cil.out.yml
- [x] loops/s3.yml
- [x] openssl-simplified/s3_clnt_1.cil-2.yml
- [x] openssl-simplified/s3_clnt_2.cil-1.yml
- [x] openssl-simplified/s3_clnt_3.cil-2.yml
- [x] openssl-simplified/s3_clnt_4.cil-2.yml
- [x] openssl-simplified/s3_srvr_1.cil-1.yml
- [x] openssl-simplified/s3_srvr_10.cil.yml
- [x] openssl-simplified/s3_srvr_11.cil.yml
- [x] openssl-simplified/s3_srvr_12.cil.yml
- [x] openssl-simplified/s3_srvr_13.cil.yml
- [x] openssl-simplified/s3_srvr_14.cil.yml
- [x] openssl-simplified/s3_srvr_2.cil-2.yml
- [x] openssl/s3_clnt.blast.01.i.cil-2.yml
- [x] openssl/s3_clnt.blast.02.i.cil-1.yml
- [x] openssl/s3_clnt.blast.03.i.cil-1.yml
- [x] openssl/s3_clnt.blast.04.i.cil-1.yml
- [x] openssl/s3_srvr.blast.01.i.cil-2.yml
- [x] openssl/s3_srvr.blast.02.i.cil-1.yml
- [x] openssl/s3_srvr.blast.03.i.cil.yml
- [x] openssl/s3_srvr.blast.04.i.cil.yml
- [x] openssl/s3_srvr.blast.06.i.cil-1.yml
- [x] openssl/s3_srvr.blast.07.i.cil-2.yml
- [x] openssl/s3_srvr.blast.08.i.cil-2.yml
- [x] openssl/s3_srvr.blast.09.i.cil-2.yml
- [x] openssl/s3_srvr.blast.10.i.cil-2.yml
- [x] openssl/s3_srvr.blast.11.i.cil-1.yml
- [x] openssl/s3_srvr.blast.12.i.cil-1.yml
- [x] openssl/s3_srvr.blast.13.i.cil-2.yml
- [x] openssl/s3_srvr.blast.14.i.cil-2.yml
- [x] openssl/s3_srvr.blast.15.i.cil-1.yml
- [x] openssl/s3_srvr.blast.16.i.cil-1.yml
- [x] bitvector/s3_clnt_2.BV.c.cil-2a.yml
- [x] bitvector/s3_clnt_3.BV.c.cil-2a.yml

With a longer timeout, we also get (after ~4 min):

- [x] seq-mthreaded-reduced/pals_opt-floodmax.5.1.ufo.BOUNDED-10.pals.c.v+lhb-reducer.ym
- [x] seq-mthreaded-reduced/pals_opt-floodmax.5.3.ufo.BOUNDED-10.pals.c.v+lhb-reducer.yml
- [x] seq-mthreaded-reduced/pals_opt-floodmax.5.4.ufo.BOUNDED-10.pals.c.v+lhb-reducer.yml

---
From no-overflow property unsoundness from SV-COMP prerun (https://github.com/goblint/analyzer/commit/cbd79873):
- [x] bitvector/s3_clnt_1.BV.c.cil-1a (no-overflow)
- [x] bitvector/s3_clnt_1.BV.c.cil-2a (no-overflow)
- [x] bitvector/s3_srvr_1a_alt.BV.c.cil (no-overflow)

---

Unsoundness at commit b87225c8:
- [x] goblint-regression/13-privatized_48-pfscan_protected_loop_minimal_unknown_1_pos
- [x] goblint-regression/13-privatized_49-refine-protected-loop_unknown_1_pos
- [x] goblint-regression/13-privatized_50-pfscan_protected_loop_minimal2_unknown_1_pos
- [x] goblint-regression/13-privatized_51-refine-protected-loop2_unknown_1_pos

**Comment by michael-schwarz** [comment]
Overall, there are 40 unsoundnesses (even with a 1 minute timeout). I think it makes sense to also track those here.

[master-e168a4e2884c9c-svcomp-json-default.zip](https://github.com/goblint/analyzer/files/7343232/master-e168a4e2884c9c-svcomp-json-default.zip)

**Comment by michael-schwarz** [comment]
> I suppose your run already included `e00a994`?

Yup, I ran on 497d7b32f.

**Comment by sim642** [comment]
Running with `--enable dbg.cfg.loop-clusters` shows it to have the following stupid CFG (SCC in the rectangle):
![image](https://user-images.githubusercontent.com/378740/137970777-cbac4165-d6c4-400a-98e6-39d708729756.png)

The strict loop entry logic forces node 9 to be bottom because it's considered a loop entry (incoming edge from another SCC from node 7) and that node is bottom.

Not yet sure if this bug only occurs due to the stupid CFG or there is any proper cases where the strict loop mechanism also is wrong.

**Comment by michael-schwarz** [comment]
> No-overflow should be true, but we find an overflow:

This is to be expected. Was it actually no-overflow where we were unsound here, @sim642? Or reach safety?

> No-overflow should be false, but we never find an overflow:

These are worrying.

**Comment by sim642** [comment]
Unsoundness is no more! https://gitlab.com/sosy-lab/benchmarking/sv-benchmarks/-/merge_requests/1332

#426 hasn't been fixed, but that doesn't show on sv-benchmarks, so we're good enough for now. If something pops up, this issue can be reopened.

**Comment by sim642** [comment]
For completeness I'll mention it here: #438 introduced some unsoundness temporarily, but that was fixed by #446. SV-COMP prerun confirms that there are no unsound cases any more again.
