### ISSUE TITLE
`exp.solver.td3.side_widen` option `sides` for context-sensitive analysis with privatization enabled can lead to non-termination

### ISSUE THREAD

**Issue by michael-schwarz** [goblint/analyzer#390]
Once again in the course of #379, I realized another potential problem with `sides` when it is combined with privatizations.

For the purpose of making something a widening point, side-effects from the same program point but in different contexts are considered different (as they correspond to different constraint system variables). However, this is a bit too conservative in placing widening points for some programs, leading to behavior where one still counts up the value stored at a global in steps of two.

One can reproduce this issue with just the default privatization after enabling a domain with (quasi) infinite ascending chains (e.g. intervals) and our test case `04/05-lockfuns.c`

~~~C
// PARAM: --enable ana.int.interval
#include <pthread.h>
#include <stdio.h>

int myglobal;
pthread_mutex_t mutex = PTHREAD_MUTEX_INITIALIZER;

void lock() {
  pthread_mutex_lock(&mutex);
}

void unlock() {
  pthread_mutex_unlock(&mutex);
}


void *t_fun(void *arg) {
  lock();
  myglobal++; // NORACE
  unlock();
  return NULL;
}


int main(void) {
  pthread_t id;
  pthread_create(&id, NULL, t_fun, NULL);
  lock();
  myglobal++; // NORACE
  unlock();
  pthread_join (id, NULL);
  return 0;
}
~~~

Here, with default privatization the publishing happens inside the call to `unlock()`. However the privatized value here is part of the context (which is in general desirable). The first time the value of `[1,1]` will be side-effected from the call to unlock with `myglobal -> [1,1]` in the context. Next time, the value of `[1,3]` will be side-effected from the call to unlock with  `myglobal -> [1,3]` in the context.  Thus, there never are increasing side-effects from the same variable, so `myglobal` never becomes a widening point, which in turn means that the call to `unlock()` happens in a new context every time.

**This is not a bug with the widening strategy `sides`, it does exactly what it says it does.**

However, I wonder if it should be our default then or if we should come up with some logic that does place widening points at globals once two increasing side-effects came from the same program point (regardless of context)? Or maybe require the always strategy as soon as a privatization is enabled?

**Comment by michael-schwarz** [comment]
I ran a benchmark of sv-comp with this `sides-pp` vs `sides`. At least with a `60s` timeout, nothing too interesting going on; might try later with 15mins.

`2021-10-13 14:40:43 CEST` is `sides` and `2021-10-13 16:50:41 CEST` is `sides-pp`.

[sides-vs-sidespp.zip](https://github.com/goblint/analyzer/files/7343347/sides-vs-sidespp.zip)

**Comment by sim642** [comment]
Since #379 was merged containing `sides-pp` (although not as default), we have a workaround for it now, so I think the issue can be closed.
