### ISSUE TITLE
Add unknown thread ID

### ISSUE THREAD

**Issue by sim642** [goblint/analyzer#392]
As revealed in #388, it would be very good to have an unknown thread ID, just like the unknown address in address sets. This would allow keeping known thread IDs while invalidating/joining with incompatible/etc.

**Comment by michael-schwarz** [comment]
Anything left to be done here now that #1224 is merged?

**Comment by sim642** [comment]
I don't think so. Looks like the issue just wasn't fully linked with the PR.
