### ISSUE TITLE
make `dune build` work?

### ISSUE THREAD

**Issue by vogler** [goblint/analyzer#399]
> Maybe we should add some dune rule for generating or at least checking `goblint.opam` and `goblint.opam.locked` when `goblint.opam.template` changes.

This would happen if we build everything with `dune build` directly, instead of having `make` just compile the `.exe` target. But I think then it also tries to do the JS build, which last I tried failed for me (JS dependencies aren't declared?).

_Originally posted by @sim642 in https://github.com/goblint/analyzer/issues/311#issuecomment-943197069_

**Comment by sim642** [comment]
> Can maybe `js_of_ocaml`/`benchmark` be optional instead of part of the default build?

That's a good idea! Will `dune build` then actually succeed and not try to do any js_of_ocaml things?

**Comment by michael-schwarz** [comment]
@keremc ?

**Comment by keremc** [comment]
I don't think removing the `js` mode (from the executable target) would cause any issues.

**Comment by sim642** [comment]
I removed the `js` mode on master and also added the `benchmark` dependency. For some reason dune's `(optional)` doesn't seem to work to optionally not compile the bench executable if it has missing dependencies.

But `dune build` now should work at least.
