### ISSUE TITLE
improve regression test script

### ISSUE THREAD

**Issue by vogler** [goblint/analyzer#42]
- update_suite.rb and pupdate_suite.rb have diverged - is there a reason for keeping the non-parallel version?
- failed tests should be printed as such right away, so that one can abort early
- exceptions should be detected
- there should be a timeout for each test
- tests that run with multiple configs (e.g. solver tests where each test runs with every solver)
- #41 
- complaints of the verifier should also be taken into account (currently tests can succeed despite not having reached a fix-point)

**Comment by vesalvojdani** [comment]
Seems the main reason running tests in parallel fails is that we need to create the tmp dir properly, or at least with some unique name.

**Comment by vogler** [comment]
This seems to be fixed, except for:
- tests that run with multiple configs (e.g. solver tests where each test runs with every solver)
- #41
