### ISSUE TITLE
Investigate widenings with thresholds for Apron

### ISSUE THREAD

**Issue by michael-schwarz** [goblint/analyzer#420]
We should investigate if we can use `widening_threshold` (from http://apron.cri.ensmp.fr/library/0.9.10/mlapronidl/Abstract1.html), or `widening_thresholds` (from http://apron.cri.ensmp.fr/library/0.9.10/mlapronidl/Oct.html) where we use Apron Domains, to maybe be more precise on examples such as tests/regression/36-apron/90-mine14-5b.c, that currently work only if we replace join with widening.

Candidates might e.g. be all constant appearing the program.

This might also be needed to succeed on Mukherjee's examples that @ivanazuzic is extracting.

**Comment by sim642** [comment]
I think we can close this because #421 got merged into #379.
