### ISSUE TITLE
Add qsort implementation to headers

### ISSUE THREAD

**Issue by jerhard** [goblint/analyzer#426]
We identified an unsoundness for an SV-Comp benchmark involving a call to qsort, where the reachability of a program point within the passed comparator function was asked for, see https://github.com/goblint/analyzer/issues/382#issuecomment-949382913.

One idea to fix this we discussed today is providing an implementation of `qsort` from a standard library that could be used within the analysis of user code.

**Comment by michael-schwarz** [comment]
From the Slack:
>  Actually, adding the implementation might not be enough. The violation we are supposed to find the violation that the compare might be call with a null pointer, but an actual implementation will probably never do that.

**Comment by sim642** [comment]
According to the `cut-3.c` file those `reach_error`s have been converted from an assertion, which maybe does actually hold, but the benchmark has been labeled wrong like the other busybox ReachSafety ones?
