### ISSUE TITLE
Questions about options to print more detailed analysis results

### ISSUE THREAD

**Issue by Medowhill** [goblint/analyzer#432]
Hi. I have questions about options to print analysis results.

1. Is there an option to print the mutexes protecting each memory location (or the locations protected by each mutex)? For example, if a global variable `myglobal` is protected by `mymutex` and the `data` field of `struct myst` is protected by `mutex` in the same struct, my expectation is
```
myglobal: { mymutex }
(struct myst).data: { *.mutex }
```
(or with whatever format). In simple cases involving only global variables without arrays, structs, and `malloc`, `dump_globs` seems useful. However, it doesn't seem to show the exact information I want in complex cases. I can use `allglobs` to get the information of every access, but it shows additional data as well, so I'm wondering whether there's an option for a concise output.

2. Is there an option to print the mutexes held at each program point? For example, when there are custom lock/unlock functions like below, `s->mymutex` must be held at the entry of `unlock`, assuming they're used properly.
```c
void lock(mystruct *s) { pthread_mutex_lock(&s->mymutex); }
void unlock(mystruct *s) { pthread_mutex_unlock(&s->mymutex); }
```
I expect Goblint must keep such information internally during its analysis, but I'm wondering whether it provides an option to print that information.

Thank you!

**Comment by vesalvojdani** [comment]
At the moment, goblint's outputting is very much all or nothing. We have various attempts at displaying results in IDEs, but presenting the most relevant information in a concise user-friendly manner is a very good idea. What we do ourselves is to view the results in the [HTML output](https://goblint.readthedocs.io/en/latest/user-guide/inspecting/). This should show the mutex sets (together with everything else...). I think adding the sort of filtered output suggested above is a good idea.

**Comment by sim642** [comment]
The HTML output internally is based on the XML output, which you can get with `--set result fast_xml -o out.xml`. So if you want to programmatically extract some information, then that should be possible, although the format is probably not very user-friendly.

**Comment by Medowhill** [comment]
Wow, the XML output option is awesome. And the HTML view is also really useful. Thanks!
