### ISSUE TITLE
Benchmarking: Add Apron-Analysis option for relational local states and non-relational globals

### ISSUE THREAD

**Issue by jerhard** [goblint/analyzer#435]
## Motivation
We want to benchmark the impact of having relational information for global variables. 

## Background
With #433, we can compare runs of the Apron analysis with different Apron domains, e.g. with octagons and intervals ("Boxes"). 
However, an analysis with octagons will in many cases already be more precise than an analysis with intervals, no matter whether relational information for global variables is found out or not in the analysis using octagons. This is simply because the octagons will yield more precise results for local computations. 

## Goal
There should be a mode where only interval information is kept about globals, while local states contain relational information. 
This could then be compared to a setting where both globals and local states have relational information, to check whether the relational information we obtain about globals actually yields any benefit in precision.

## Remark
This feature is primarily intended for benchmarking, not actual usage.

**Comment by sim642** [comment]
Closing for now since this wasn't used for the evaluation and there's no need to have this permanently.
