### ISSUE TITLE
Array out of bounds check runs into an exception

### ISSUE THREAD

**Issue by karoliineh** [goblint/analyzer#451]
When running goblint on file [bench/linux/drivers/char/lp.c](https://github.com/goblint/bench/blob/master/linux/drivers/char/lp.c) with conf:

```
{
  "kernel": true,
  "kernel-root": "goblint/analyzer/linux-headers",
  "ana": {
    "int": {
      "interval": true
    },
    "arrayoob": true
  }
}
```

goblint exits with

`Fatal error: exception IntDomain.ArithmeticOnIntegerBot("[-9223372036854775808,9223372036854775807] op bottom")`

**Comment by michael-schwarz** [comment]
What is always very helpful in a case such as this, is if you can reduce the size of the program to a minimal example where this still happens. That often allows finding the problem quite easily.

**Comment by sim642** [comment]
The exception is coming from this upper bound comparison with length, where the length is the `bottom` in the exception:
https://github.com/goblint/analyzer/blob/fdaf34b8d3ae2398efc6899fbdd1550d94f4cd22/src/cdomains/arrayDomain.ml#L576

I'm not sure how it's supposed to be, but it seems to be that after global initializers the array has bottom length in the trivial array domain. I think the global initializer for it will somehow set the unknown all indices to the values in a bottom array, which leaves length bottom:
https://github.com/goblint/analyzer/blob/fdaf34b8d3ae2398efc6899fbdd1550d94f4cd22/src/cdomains/valueDomain.ml#L992-L995

**Comment by michael-schwarz** [comment]
The problem is due to `exp.fast_global_inits`. If I disable that, it works.
