### ISSUE TITLE
Exclude `stdlib.c` when using `--enable justcil`

### ISSUE THREAD

**Issue by michael-schwarz** [goblint/analyzer#478]
`justcil` thus far was very helpful (e.g. for people who are new to the project) to understand what CIL does to code.
That is somehow not the case so much anymore, as most of the output now is the cilled version of `stdlib.c`, and one has to go to hunting for the actual user code (that is somewhere after the headers but before these defintions).

What do you think about not including`stdlib.c` when using `justcil` and instead emitting a comment that is ommited?

**Comment by sim642** [comment]
We already have one hack for `justcil` and this would be another:
https://github.com/goblint/analyzer/blob/7d9508647ae034485af50ab7205db990adc0fb62/src/util/cilfacade.ml#L97-L105

But here's a question: why does this need to be part of the main Goblint binary at all?! We could easily have a secondary binary that does this. Or even better, have such thing be part of goblint-cil itself.

**Comment by michael-schwarz** [comment]
> But here's a question: why does this need to be part of the main Goblint binary at all?!

As we will start having some transformations (e.g. loop unrolling) in Goblint (on top of, e.g., the instrumentation that is already there for the termination analysis), I think it becomes increasingly impractical to separate this out. Especially since it is precisely in these cases that the output is also helpful for more seasoned Goblint developers.

> Or even better, have such thing be part of `goblint-cil` itself.

`goblint-cil` can already do this.

**Comment by sim642** [comment]
Fair enough, although the moment you include anything from the standard library you get all the same unreadable stuff, so this `justcil` output is only nice in small completely closed programs. If you're interested in a particular file (or don't want to include standard libraries), maybe it would be better to allow choosing which files `justcil` should print?

**Comment by vogler** [comment]
> most of the output now is the cilled version of `stdlib.c`, and one has to go to hunting for the actual user code (that is somewhere after the headers but before these defintions).

Why does it come after the user code and not before?

**Comment by sim642** [comment]
I guess it's just a matter of which order they're preprocessed and merged in, but shouldn't really matter for merging (/linking). This might also have changed due to #448. Should be easy enough to make `stdlib.c` come first in the `justcil` output at least. Then for simple programs the user code in the single source file ends up at the tail of the output and viewable with least scrolling.
