### ISSUE TITLE
Robust `make deps` that works like `rm _opam && make setup`

### ISSUE THREAD

**Issue by vesalvojdani** [goblint/analyzer#507]
Do we have some command that works like `rm _opam && make setup`? I recently tried to make `make deps` more like that, but this doesn't work for the recent version bump. For some reason, the batteries version does not get upgraded. This was particularly annoying when master and interactive where on different versions, but I think we ought to have some convent way to reset the build environment properly. What to the rest of you do for this? (other than `rm _opam`?)

**Comment by sim642** [comment]
> I recently tried to make `make deps` more like that, but this doesn't work for the recent version bump. For some reason, the batteries version does not get upgraded.

What was the error then? Both the locked and the unlocked opam file demand batteries 3.4.0 right now, so there's no way it could succeed without upgrading or erroring about unsatisfiable constraints.

**Comment by vesalvojdani** [comment]
Well, this is the output:
```
vesal@Skaro analyzer % ./make.sh deps
[ERROR] Package conflict!
  * Missing dependency:
    - batteries >= 3.4.0
    no matching version

No solution found, exiting

<><> Synchronising pinned packages ><><><><><><><><><><><><><><><><><><><><><><>
[ppx_deriving.5.2.1] synchronised (no changes)
[goblint-cil.1.8.2] synchronised (no changes)
[apron.v0.9.13] synchronised (no changes)

Already up-to-date.
Nothing to do.
```

So the first attempt to update fails, but then the other thing succeeds without upgrading batteries. Now when I checked out 1f687fb401dad621cb3e5471cfcfbc48c2642be7, it downgraded to 3.12 and rebuilt everything. Then when back to master it seems to work again, so I can't really reproduce this behavior. But it did behave the same on the local machine and the server.

**Comment by sim642** [comment]
Looks like the first case of `make deps` doesn't fail correctly (`opam install` fails, but it continues to `opam upgrade`, which succeeds). It needs to fail overall (the command need to be joined with `&&`?) because the `opam update` in the second case is what's needed to update the opam repository to find out that batteries 3.4.0 exists.

Probably cannot reproduce anymore because `~/.opam` has the repository updated already.

**Comment by vesalvojdani** [comment]
Ah, yes, the first attempt does succeed... most likely `&&` would fix it. I might have backup directory I can try this on.

**Comment by sim642** [comment]
`~/.opam` is different from `./_opam`, so you'd need a different user with an outdated opam repository. And making a new one doesn't help because there's no way to download that outdated repository any more.
