### ISSUE TITLE
save/compare analysis results

### ISSUE THREAD

**Issue by vogler** [goblint/analyzer#51]
Useful for:
- refactoring
- improvement in precision

Is marshalling the result hashtables good enough?

**Comment by jerhard** [comment]
For the purpose of incremental analysis with td3, I implemented code to store the solver results to disc via marshalling. It's specific to td3, however, and not implemented for other solvers. 

I guess marshalling should work for other solvers, too. The question is whether we are still interested in implementing it doing this.

**Comment by vogler** [comment]
This has been implemented in
5f58ee87e02f01bf8e66240c53f0c5e91d748fb3
96efc0a1dfa6fa41ef9abbfa275d19954ff2d0de
b2525d1df4d43d6d69b2c8c32ba4498ce2133292
27895b8ab221fc9ac1a9215a6b852f89545fdb1b
fe8ce4084c5a40218bf7d2375695bf28a6922630
23e0fc50bd81d9b5f5ef6406f7f7bfd91473f30a
