### ISSUE TITLE
Partitioned arrays yield unsound value when accessed at very large index

### ISSUE THREAD

**Issue by jerhard** [goblint/analyzer#511]
There is an unsoundness in partitioned arrays for very large arrays, namely claiming a wrong value, when checking the value at an index that is at least as big as the following `j`: 
```C
long j = LONG_MAX - 6442450943;
```
This index is smaller than the maximum value of `ptrdiff_t`, which we assume (with the default CIL configuration) to have 8 bytes, i.e. be as large as `long`. 

See the failing test case [here](https://github.com/goblint/analyzer/blob/part_large_array_unsoundness/tests/regression/22-partitioned_arrays/17-large_arrays.c). This test fails whether applying the changes in #510 or not.

This is issue is somewhat obscure of course, as there really are no computers with >9 Exabyte main memory as of now that the code in question could run on.

**Comment by michael-schwarz** [comment]
The issue that is unsound only shows up if the array is allocated with `calloc(...)`, if it is stack-allocated, it is still imprecise but not unsound.

So I guess there is some strange interaction with blobs.
