### ISSUE TITLE
handle integers correctly

### ISSUE THREAD

**Issue by vogler** [goblint/analyzer#52]
- `Integers` internal representation is int64 (signed)
- `Interval32` -> `Interval (I : S)`
- `Interval64 = Interval (Integers)`
- add type argument to all int operations
- errors (e.g. `Div_by_zero`)? see #55
  - old: bottom
  - new: `M.warn [Undefined] "div. by zero"`, top?
- get rid of `Trier`
- Big_int, uint?

**Comment by jerhard** [comment]
The integer domains now have been ported to Big_int.
