### ISSUE TITLE
refactor privatization code

### ISSUE THREAD

**Issue by vogler** [goblint/analyzer#53]

**Comment by sim642** [comment]
Whatever was the original intention with this issue, I think we can consider it sufficiently refactored after #183.

**Comment by michael-schwarz** [comment]
Should this cleanup not entail removing the `old` (unsound!) privatization too?

(At a time where comparison with it ceases to be interesting.)

**Comment by sim642** [comment]
In some distant future, yes, but for the time being I'd rather keep `old` around as possible past-reference in case issues with the other come up or corner cases that they haven't been thoroughly been validated for, e.g. OSEK, `earlyglobs` and possibly something else.

But keeping a very vague issue without a specific end goal or timeframe isn't very useful anyway. It'll just get forgotten and buried like this one. And anyone changing `exp.privatization` should probably look at the module and see the note about unsoundness. So in that sense it's not much different than other options (with less documentation) that toggle unsound behavior.
