### ISSUE TITLE
IntDomTuple only compares activated domains

### ISSUE THREAD

**Issue by sim642** [goblint/analyzer#541]
Here's the implementation of its `equal`:
https://github.com/goblint/analyzer/blob/b9995c8d8ab5d1677b72168b44be3b6b29b5a82d/src/cdomains/intDomain.ml#L2730-L2732
Here's `map2p`:
https://github.com/goblint/analyzer/blob/b9995c8d8ab5d1677b72168b44be3b6b29b5a82d/src/cdomains/intDomain.ml#L2717-L2721
And here's `opt_map2`, which ignores the case of `Some x, None`:
https://github.com/goblint/analyzer/blob/b9995c8d8ab5d1677b72168b44be3b6b29b5a82d/src/cdomains/intDomain.ml#L2636-L2637
And here's how `for_all` is implemented:
https://github.com/goblint/analyzer/blob/b9995c8d8ab5d1677b72168b44be3b6b29b5a82d/src/cdomains/intDomain.ml#L2639-L2641
As the comment about `to_list` says, it filters out only the activated domains.

Therefore `(Some defexc, None, None, None)` and `(Some defexc, Some interval, None, None)` are considered equal.
This in turn breaks incremental precision improvement annotations: even if the new more precise analysis projects the previously only def_exc context into a def_exc+interval context, then in the solver's hashtable, that yields a constraint variable, which is `equal` to the old one. Hence the more precise context is never actually created and the result doesn't get more precise!

The same applies to `compare` and probably most of the functions using `to_list` or `opt_map2`. This wasn't a problem before #395 because IntDomTuples with different activations never occurred during a single run of Goblint (since the activation was effectively fixed by the options). So `opt_map2` ignoring `Some x, None` never happened and `to_list` didn't filter anything like that out.
But this is now possible and IntDomTuple should be fixed to account for this. At minimum, the identity operations (`equal`, `compare`, `hash`) must handle these cases not to swallow more precise values like this. Other integer domain operations don't have to handle these cases (the projections in base analysis should ensure that), but they should throw exceptions if that somehow ever happens to not quietly hide such issues.

**Comment by sim642** [comment]
Actually I now remembered that the type of `IntDomTuple` isn't even anything exotic (unlike `MCP`):
https://github.com/goblint/analyzer/blob/b9995c8d8ab5d1677b72168b44be3b6b29b5a82d/src/cdomains/intDomain.ml#L2605-L2606
So it should be possible to just flat out derive `eq` and `ord` for it (and manually write `hash` until #542) without using any of the complicated polymorphic first-class module trickery that goes on later in the module to account for activated.

**Comment by jerhard** [comment]
Do you have an actual example where this causes issues? I tried to create an example in #546, but this works, even if I set the `hash`-function of `IntDomTuple` to a constant for testing purposes.

**Comment by sim642** [comment]
There's a CI failure in #542 which I believe happens because of this.

**Comment by jerhard** [comment]
Cherry-picking 09cb83d095debe5d9b941c343fd86e5b7a28169b onto #542 (`ppx_deriving_hash`) indeed fixes the failure.

**Comment by jerhard** [comment]
@sim642 Would you prefer cherry-picking 09cb83d into #542 or should we merge #546 into `master` instead?
