### ISSUE TITLE
Optimize `MCP` assoc lists

### ISSUE THREAD

**Issue by sim642** [goblint/analyzer#572]
`MCP` extensively uses assoc lists to represent a dynamic product of analyses (i.e. their domain elements, contexts, etc). Manipulating these involves lots of `assoc` calls to look up corresponding analysis values in other lists. From profiling I have noticed this have a nontrivial impact where `List.assoc` takes ~10% of Goblint's total runtime!

Assoc lists are famously not performance-oriented, so it makes sense to improve this. Currently I see two possibilities:
1. Replace assoc lists with `Map`.
2. Ensure well-defined and consistent order of elements (e.g. sorted by analysis index) in the assoc lists such that operations can just zip two/three of those lists together. This would allow manipulating corresponding elements pairwise without having to do `assoc` calls.

**Comment by michael-schwarz** [comment]
> Ensure well-defined and consistent order of elements (e.g. sorted by analysis index) in the assoc lists such that operations can just zip two/three of those lists together.

Do we not already have this anyway? We do a `topo_sort` of the analyses at least, and one would think that all of the places in MCP where we manipulate such things should use the same order?

**Comment by sim642** [comment]
> Do we not already have this anyway? We do a `topo_sort` of the analyses at least, and one would think that all of the places in MCP where we manipulate such things should use the same order?

I suspect it mostly is indeed because in all the output, the values are always in consistent order and they're printed just based on the list order, not sorting by analysis indices.
`topo_sort` only does a topological sorting according to analysis dependencies, such that `presub` and `postsub` would work. But a topological sorting itself is not necessarily unique.

So things might just work out already, but for some reason zipping hasn't been used and instead there's all the `assoc` stuff to handle the more general case of no consistent order. I don't know why that is, but it at least shows that no care has been given to actually ensure a fixed order. So if we transition to it, we should probably have some `assert`s in the code to quickly identify it possibly breaking, since otherwise `Obj` will just cause random segfaults.
