### ISSUE TITLE
support constants >int64

### ISSUE THREAD

**Issue by vogler** [goblint/analyzer#59]
CIL's [CInt64](http://cil-project.github.io/cil/doc/html/cil/api/Cil.html#TYPEconstant) is only ok for constants that fit in OCaml's `int64` (signed). Anything bigger silently overflows.
The constructor has a `string option` which should contain the original literal, but unfortunately it's always `None`.

**Comment by michael-schwarz** [comment]
I guess @jerhard fixed this during the revamp of the int domains? 
(one of the related commits is e.g. d99f4c3c97815fc5ae3a236b3503786e831ffc38)

If yes, we can close this.

**Comment by vogler** [comment]
https://github.com/goblint/analyzer/search?q=d99f4c3c97815fc5ae3a236b3503786e831ffc38&type=commits
doesn't find anything and https://github.com/goblint/analyzer/commit/d99f4c3c97815fc5ae3a236b3503786e831ffc38 is 404.

**Comment by michael-schwarz** [comment]
Sorry, that particular commit is a related fix in CIL:
https://github.com/goblint/cil/commit/d99f4c3c97815fc5ae3a236b3503786e831ffc38

**Comment by vogler** [comment]
Related PRs:
#159 Port the DefExc Domain to use BigInts
#175 Port the Enums domain to bigint

So, we have >=int64 precision for all int domains (`ana.int.def_exc`, `ana.int.interval`, `ana.int.enums`)?

Related tests:
https://github.com/goblint/analyzer/blob/master/tests/regression/01-cpa/43-large-n-div.c
https://github.com/goblint/analyzer/blob/master/tests/regression/31-ikind-aware-ints/07-defexc-large.c
https://github.com/goblint/analyzer/blob/master/tests/regression/31-ikind-aware-ints/13-intervals-large.c
https://github.com/goblint/analyzer/blob/master/tests/regression/31-ikind-aware-ints/14-enums-large.c

**Comment by michael-schwarz** [comment]
> So, we have >=int64 precision for all int domains (ana.int.def_exc, ana.int.interval, ana.int.enums)?

That depends on what you mean by it:
The test cases from above where things are still `//UNKNOWN` are cases where one could improve precision for unsigned types and when assuming wrap-around for signed types. Such improvements are, e.g., handling must-overflows for intervals and using the same logic that is used in the definite case in `def_exc` also for `enums`, ...). Related #161 
 
We could do this if we want to, but then we should rename the issue and modify the description to talk about such precision improvements.

The unsoundness the issue talks about 

>  Anything bigger silently overflows.

is fixed as far as I understand. (@jerhard correct me if I'm wrong)

**Comment by jerhard** [comment]
>The unsoundness the issue talks about

>>    Anything bigger silently overflows.

>is fixed as far as I understand.

@michael-schwarz Yes, this should be fixed and I think we can close this issue. If something particular comes up, e.g. a bug, or we want precision improvements for some particular domain, we can create a new issue.
