### ISSUE TITLE
IDE/editor plugin

### ISSUE THREAD

**Issue by vogler** [goblint/analyzer#62]
The eclipse plugin is no longer supported.
It would be nice to have some plugin for:
- visual studio code
- sublime text
- vim/emacs
- ...

**Comment by michael-schwarz** [comment]
A student is working on an integration for VSCode for their Bachelor's thesis.

**Comment by michael-schwarz** [comment]
Since we have not heard from the student that their deadline was extended and it the deadline was on 11/15/20, I don't think they'll hand anything in.

**Comment by sim642** [comment]
I'll also copy here what I said in the #interactive Slack channel:

> Regarding IDE integration I once happened upon this: https://github.com/MagpieBridge/MagpieBridge. It seems like it's supposed to be like LSP (language server protocol) or DAP (debug adapter protocol) but for static analyzer integration. Might be useful for us to do IDE integrations via such protocol instead of developing IDE plugins from scratch. I haven't looked more at it and there might be other competing standards with the same goal.

**Comment by vesalvojdani** [comment]
Issues can be tracked at [GobView](https://github.com/goblint/gobview) and [GobPie](https://github.com/goblint/GobPie).
