### ISSUE TITLE
Failed incremental runs without incremental postsolver

### ISSUE THREAD

**Issue by stilscher** [goblint/analyzer#635]
When running the pairwise benchmarking on zstd without the incremental postsolver several incremental runs failed that did not fail before (disabling `incremental.verify` was the only change). In the log of the incremental run I found several 'Fixpoint not reached at ...' statements. For example:
```
Fixpoint not reached at either varinfo * std option * std or varinfo:(NONE, (struct __anonstruct__sigfault_1040180430).si_addr)
Origin: node 40650 "newVersion == 5U" on ../lib/decompress/../legacy/zstd_legacy.h:305:9-312:9
 Solver computed:
 bot
 Side-effect:
 lifted Set (std) and Set (varinfo * std option * std):{100, false, ../lib/decompress/../legacy/zstd_legacy.h:284:36-284:93, & *legacyContext, [mhp:{tid=[main]; created={[main, POOL_thread@../lib/common/pool.c:151:13-155:9], [main, POOL_thread@../lib/common/pool.c:232:17-235:13]}},
                                                                                                                                                thread:[main]]}
 Difference: lifted Set (std) and Set (varinfo * std option * std):{100, false, ../lib/decompress/../legacy/zstd_legacy.h:284:36-284:93, & *legacyContext, [mhp:{tid=[main]; created={[main, POOL_thread@../lib/common/pool.c:151:13-155:9], [main, POOL_thread@../lib/common/pool.c:232:17-235:13]}},
```
Also, the failed incremental run without incremental postsolver takes ~3min whereas the incremental run in the setup with incremental postsolver takes only around ~40s.

The problem should be reproducible with:

- Branch: interactive
- Commit analyzed non-incrementally: https://github.com/facebook/zstd/commit/621d79898811d42529dbabebe7a2d7d5cb0e8dcd
- Commit analyzed incrementally: https://github.com/facebook/zstd/commit/0178c12dd98ad5e63968b12eaaf32e3162a0ffee
- Configuration:
```
{
  "ana": {
    "base": {
      "privatization": "none"
    }
  },
  "sem": {
    "unknown_function": {
      "spawn": false
    }
  },
  "incremental": {
    "reluctant": {
      "compare": "leq"
    },
    "restart": {
      "sided": {
        "enabled": false
      }
    },
    "verify": false
  },
  "solvers": {
    "td3": {
      "restart": {
        "wpoint": {
          "enabled": false
        }
      }
    }
  },
  "exp": {
    "earlyglobs": true
  },
  "dbg": {
    "print_dead_code": true
  },
  "pre": {
    "cppflags": ["-DZSTD_NO_INTRINSICS", "-D_FORTIFY_SOURCE=0", "-DGOBLINT_NO_ASSERT", "-DGOBLINT_NO_BSEARCH", "-D__LINE__=0"]
  },
  "printstats": true,
  "warn": {
    "assert": false,
    "behavior": false,
    "integer": false,
    "cast": false,
    "race": true,
    "deadcode": false,
    "analyzer": false,
    "unsound": false,
    "imprecise": false,
    "unknown": false,
    "error": false,
    "warning": true,
    "info": false,
    "debug": false,
    "success": false
  }
}
```

1. checkout parent commit in zstd repo and run
```
sed -i 's/zstd : CPPFLAGS += -DZSTD_LEGACY_SUPPORT=$(ZSTD_LEGACY_SUPPORT).*/zstd : CPPFLAGS += -DZSTD_LEGACY_SUPPORT=$(ZSTD_LEGACY_SUPPORT) -DZSTD_NO_INTRINSICS/' programs/Makefile
LC_ALL=C.UTF-8 compiledb make zstd
```
2. `./goblint --conf [config file mentioned above] --disable incremental.load --enable incremental.save [path to zstd repo]` 
3. repeat 1. and 2. for the child commit enabling `incremental load` and disabling `incremental.save`

**Comment by michael-schwarz** [comment]
This seems to be related to accesses, maybe @sim642 has a hunch what's happening?

**Comment by sim642** [comment]
Somehow all the `HACK`ery that currently goes into pretending that access side effects during postsolving shouldn't emit verify errors is somehow failing here. #634 would get rid of these hacks and hopefully also fix this issue.

**Comment by sim642** [comment]
@stilscher Could you check if this still happens after #634 was merged to `interactive`?

**Comment by michael-schwarz** [comment]
@stilscher: is this fixed now and can we close it?
