### ISSUE TITLE
include more information about accesses

### ISSUE THREAD

**Issue by vogler** [goblint/analyzer#65]
We currently only output the line of an access.

For multiple accesses in one line it might be good to have:
- the starting index within the line

**Comment by michael-schwarz** [comment]
The issue is stale, Goblint does currently output a more detailed location for accesses.

**Comment by sim642** [comment]
All the accesses have the statement's location (including column) though, because we don't have locations for each subexpression individually.

**Comment by michael-schwarz** [comment]
True, but the case where there are several accesses to the same global in an expression is probably exceedingly rare (and not worth polluting CIL expressions with locations IMO).
