### ISSUE TITLE
Apron precision dumps taking an unproportionate amount of time

### ISSUE THREAD

**Issue by michael-schwarz** [goblint/analyzer#668]
Taking a closer look at our numbers for the "More Traces" paper, I realized the following. Enabling  `exp.apron.prec-dump` leads to a serious performance hit for some of the programs.

For `knot_comb.c` **without** `exp.apron.prec-dump` :

`/home/michael/Documents/goblint-cil/analyzer/goblint --conf /home/michael/Documents/goblint-cil/analyzer/conf/traces-rel.json --set dbg.timeout 900 --set ana.activated[+] apron --set ana.path_sens[+] threadflag --set ana.apron.privatization mutex-meet ../bench/pthread/knot_comb.c --enable dbg.uncalled --enable allglobs --enable printstats --enable dbg.debug -v --enable dbg.print_dead_code`

```
TOTAL                           6.626 s
  parse                           0.017 s
  convert to CIL                  0.026 s
  analysis                        6.584 s
    createCFG                       0.015 s
      handle                          0.004 s
      iter_connect                    0.011 s
        computeSCCs                     0.009 s
    global_inits                    0.014 s
    solving                         6.538 s
      S.Dom.equal                     0.026 s
      postsolver                      1.976 s
    warn_global                     0.006 s
      access                          0.006 s
```

vs **with** `exp.apron.prec-dump`

`/home/michael/Documents/goblint-cil/analyzer/goblint --conf /home/michael/Documents/goblint-cil/analyzer/conf/traces-rel.json --set dbg.timeout 900 --set ana.activated[+] apron --set ana.path_sens[+] threadflag --set ana.apron.privatization mutex-meet ../bench/pthread/knot_comb.c --enable dbg.uncalled --enable allglobs --enable printstats --enable dbg.debug -v --enable dbg.print_dead_code --sets exp.apron.prec-dump /home/michael/Documents/goblint-cil/bench/bench_result/knot_comb.mutex-meet.prec`

```
TOTAL                          54.936 s
  parse                           0.018 s
  convert to CIL                  0.024 s
  analysis                       54.894 s
    createCFG                       0.015 s
      handle                          0.009 s
      iter_connect                    0.006 s
        computeSCCs                     0.004 s
    global_inits                    0.019 s
    solving                         7.085 s
      S.Dom.equal                     0.026 s
      postsolver                      2.512 s
    warn_global                     0.010 s
      access                          0.009 s
    apron prec-dump                47.752 s
```

Here `47s` are spent inside of `store_data` inside the apron analysis, whereas solving only takes `7s` **(!!)**.

While this not problematic per se (implementation might just be slow for whatever reason), it seems strange. We should see why this happens and definitely need to considered this when measuring performance.

**Comment by sim642** [comment]
The conversion is just calling Apron's `to_lincons_array` and `of_lincons_array`, so there might not be much to do about it (although I guess one could `perf` it to see what Apron internals it spends time on).
The example commands above use the default octagon domain though, so the whole conversion is actually unnecessary. In that case one could use `Oct.Abstract1.is_oct` and `Oct.Abstract1.to_oct` to "magically" bypass the conversion.

**Comment by michael-schwarz** [comment]
> to "magically" bypass the conversion.

Yes, I am making a fix that does this.

> (although I guess one could `perf` it to see what Apron internals it spends time on)

For now, I'll just add a warning that it might be expensive and should be run separately to get numbers, and pull it out in the benchmark script. I think that should suffice, we don't really care about the performance of precision dumping so much (except that it should not falsify our measurements)

**Comment by sim642** [comment]
> I think that should suffice, we don't really care about the performance of precision dumping so much (except that it should not falsify our measurements)

That's true. My guess would be that `to_lincons_array` is forcing some expensive octagon closure computation everywhere, while during the analysis itself that's not necessary or something.
