### ISSUE TITLE
Pointer analysis used in Goblint

### ISSUE THREAD

**Issue by true-ryan** [goblint/analyzer#685]
Hi, I am curious about which kinds of sensitivity of pointer analysis are used in Goblint. Is it flow-insensitive and context-insensitive? Thank you.

**Comment by michael-schwarz** [comment]
Hi, thanks for your question.
By default our analysis of pointers is flow- and context-sensitive. However the degree of context-sensitivity can be configured via various options (`ana.base.context.*`) or completely turned off (by adding `base` to `ana.ctx_insens`).

There is a small caveat that, for multithreaded programs, program globals are generally handled flow-insensitively.

If you have further questions or want to know more details, feel free to ask again!

**Comment by anson-lo** [comment]
@michael-schwarz Thank you! My problem is solved.
