### ISSUE TITLE
HTML output stuck in browser

### ISSUE THREAD

**Issue by VolkerStolz** [goblint/analyzer#7]
Neither Chrome nor Safari can process the output by

    goblint --set ana.activated "[['base', 'maylocks','thread-id-location']]" --sets result html knot_comb-3.c

on [my sample file](https://github.com/VolkerStolz/bench/blob/0650a0f1c188201f69bca351b55f00a8505fc851/pthread/knot_comb-3.c).

E.g. go to line 508, and try to see analysis results.

**Comment by vesalvojdani** [comment]
This now works in recent browsers. We will eventually have to adopt a more scalable output using databases.
