### ISSUE TITLE
Detect calls of thread-unsafe functions as races

### ISSUE THREAD

**Issue by sim642** [goblint/analyzer#723]
Under "Thread-safe functions" of [pthreads man page](https://man7.org/linux/man-pages/man7/pthreads.7.html), it says the following:

> A thread-safe function is one that can be safely (i.e., it will deliver the same results regardless of whether it is) called from multiple threads at the same time.
> POSIX.1-2001 and POSIX.1-2008 require that all specified in the standard shall be thread-safe, except for following functions:

Then a list of possibly thread-unsafe functions follows.

We should consider calls to these functions (in place of global variables) and report racing calls (in place of accesses).

I was reminded of this when trying to figure out why chrony uses a global lock to protect what seems to be thread-local data manipulation. It doesn't call any functions from this list, but for completenes it would be nice to detect as well.

---

The following [thread-unsafe functions](https://man7.org/linux/man-pages/man7/pthreads.7.html) remain to be added to `libraryFunctions.ml`:
- [x] `ecvt()`
- [x] `ftw()`
- [x] `nftw()`
- [x] `setkey()`
- [x] `wcsrtombs()`
- [x] `wcstombs()`
- [x] `wctomb()`

_Originally posted by @karoliineh in https://github.com/goblint/analyzer/issues/1079#issuecomment-1584833060_

**Comment by sim642** [comment]
Related to a couple of `*_unlocked` functions from the list, turns out there are `flockfile`, `ftrylockfile` and `funlockfile`, which treat a `FILE` as a mutex. No idea, if anyone uses them, but I guess it wouldn't hurt to also consider those for mutual exclusion.

**Comment by michael-schwarz** [comment]
> Related to a couple of `*_unlocked` functions from the list, turns out there are `flockfile`, `ftrylockfile` and `funlockfile`, which treat a `FILE` as a mutex. No idea, if anyone uses them, but I guess it wouldn't hurt to also consider those for mutual exclusion.

Should we move this to a new issue?
