### ISSUE TITLE
Values of escaped globals unsoundly not passed to callee

### ISSUE THREAD

**Issue by michael-schwarz** [goblint/analyzer#755]
During #742 I discovered the following unsoundness:

~~~C
#include <assert.h>

struct list
{
    int n;
    struct list *next;
};

void *allocate_memory()
{
    return malloc(8U);
}

struct list *append(struct list *l, int n)
{
    struct list *new_el;

    new_el = allocate_memory();

    new_el->n = n;
    new_el->next = l;

    return new_el;
}

int main()
{
    struct list *l, m;
    l = &m;
    l->next = 0;
    l->n = 0;

    l = append(l, 1);
    l = append(l, 2);

    assert(l->next->next->n == 0); //UNKNOWN
}
~~~

We claim that the assert must fail, but it does hold in the concrete. It seems to be related to our `malloc` handling, as replacing `allocate_memory()` with calls to `malloc` hides the issue.

**Comment by michael-schwarz** [comment]
I added the example to this branch: https://github.com/goblint/analyzer/tree/issue_755

**Comment by sim642** [comment]
Surprisingly `--set ana.malloc.wrappers[+] allocate_memory` doesn't even help.

**Comment by michael-schwarz** [comment]
`ldv-validator-v0.6/linux-stable-af3071a-1-130_7a-drivers--hwmon--s3c-hwmon.ko-entry_point.cil.c` and `ldv-linux-3.12-rc1/linux-3.12-rc1.tar.xz-144_2a-drivers--input--touchscreen--usbtouchscreen.ko-entry_point.cil` are most likely due to the same issue (or at least not due to #742, as they happen on master).

**Comment by michael-schwarz** [comment]
The issue seems to be that `m` is treated as escaped, but no corresponding global is created for it. My guess is that we end up with `m` being bottom and hence the claim that `l->next->next->n` is not `0`.

**Comment by sim642** [comment]
There is no multithreading in the program though, so escaping shouldn't apply here and everything would be in the local state.

**Comment by michael-schwarz** [comment]
I think (one of) the issues is that globals (that became globals because they escaped into global variables) are not treated properly, i.e. are not passed to the caller in single-threaded mode. This is probably exasperated by the fact that we seem to ignore pointers that should lead to a supertop when dereferenced. The following assert incorrectly is reported as always failing.

~~~C
#include <assert.h>
int* ptr;
int nine = 9;

int other() {
    assert(*ptr == 8); //UNKNOWN!
}

int main()
{
    int g = 8;
    int top;

    if(top) {
        ptr = &g;
    } else {
        ptr = &nine;
    }

    other();
}
~~~

Related: #686 #246

**Comment by michael-schwarz** [comment]
The first benchmark seem to miss some sort of initialization (setting `s3c_hwmon_driver_group0` to anything other than what `zalloc` yields), which leads to an immediate abort in `s3c_hwmon_probe`, making code further down that is supposed to contain the call to `reach_error` unreachable.

I think it might be mislabled (CPAChecker and PESCO somehow produce a counterexample, I'll try to inspect that)

**Comment by michael-schwarz** [comment]
Extracted the two unrelated cases to #780
