### ISSUE TITLE
Unsigned long interval unsoundness with refinement

### ISSUE THREAD

**Issue by sim642** [goblint/analyzer#769]
On 37e0d70cd4c6e320c696a906896535a901aba246 we are unsound on the following program:
```c
// PARAM: --enable ana.int.interval --set ana.int.refinement once
#include <assert.h>

int main() {
  for (unsigned long i = 0; i < 1000; i++) {
    assert(1);
  }

  assert(1); // reachable
  return 0;
}
```
We claim that the second assert is dead code. The abstract value for `i` at the loop head is `def_exc:Unknown int([0,64]); intervals [0,255]`.
It's fine with `unsigned int` and just `long`.

**Comment by jerhard** [comment]
Interestingly, when additionally setting `ana.int.def_exc_widen_by_join`, the result is not unsound.

**Comment by michael-schwarz** [comment]
There are bizarre things happening with `+` here:

`For a+b, we get  a: (Unknown int([0,64]),[0,9999]), b: (1,[1,1]), res (Unknown int([0,8]),[1,10000]), ref (Unknown int([0,8]),[1,255]) `

So the issue is even before any refinement happens...

**Comment by sim642** [comment]
I guess refinement just exposes the issue which appears to be with def_exc ranges somehow.

**Comment by michael-schwarz** [comment]
Yup, I suspected an issue with the `ikind`s but they also seem to be correct... Digging deeper now

**Comment by michael-schwarz** [comment]
The culprit seems to be this piece of code here: It returns `unsigned char` as the suitable type for `18446744073709551616` which is the maximum `unsigned long`.

https://github.com/goblint/analyzer/blob/95f183423092659e32933d21c0b5c9a42d9fb7e3/src/cdomains/intDomain.ml#L400

**Comment by michael-schwarz** [comment]
In fact, the solution is quite simple: There should be no truncation here!
