### ISSUE TITLE
Extend cfg comparison with local rename mapping

### ISSUE THREAD

**Issue by stilscher** [goblint/analyzer#777]
As discussed in #731 the rename mapping introduced for detecting renames of local variables or formal parameters in the AST comparison can easily be passed through to the cfg comparison. In `updateCil.ml` one then has to update the old names of the local variables and parameters also for partially changed functions for a correct output. With this, the cfg comparison could also profit from being able to match renamed locals.

**Comment by TimOrtel** [comment]
The propagation is now implemented in [this PR](https://github.com/goblint/analyzer/pull/774). However, the actual detection of renames is not enabled nor tested. Right now, only the renamesOnSuccess are propagated.
