### ISSUE TITLE
support ocaml >= 4.08

### ISSUE THREAD

**Issue by vogler** [goblint/analyzer#78]
ppx_import blocks the upgrade to ocaml 4.08, track https://github.com/ocaml-ppx/ppx_import/issues/41.
We use ppx_import to import Cil types to generate `to_yojson` and `show` with ppx_deriving, see https://github.com/goblint/analyzer/blob/master/src/util/deriving.ml#L22.
Alternatively we could maybe include our fork https://github.com/goblint/cil as a git submodule to have direct access to the types. However, I guess, it should then not be installed as an opam package but be built together with goblint.

**Comment by fpottier** [comment]
Just a comment to say it would be good to have `ppx_import` work for OCaml 4.08 and beyond. It can be really useful in conjunction with `ppx_deriving`, `visitors`, etc.

**Comment by michael-schwarz** [comment]
The ppx_import folks seem to be working on adding support for 4.08 now :tada: https://github.com/ocaml-ppx/ppx_import/pull/46

**Comment by michael-schwarz** [comment]
Their fix solves the problem with `ppx_import`.

Unfortunately, this leaves us with [ppxx](https://bitbucket.org/camlspotter/ppxx) (which `ppx_monadic` relies on) still blocking support for 4.08.

**Comment by vogler** [comment]
I only used `ppx_monadic` in `src/extract/` to have a more concise syntax.
There are several such libraries available if you search for monad in the [packages](https://opam.ocaml.org/packages/).
OCaml 4.08 also introduced definable syntax for monads and applicatives (see [here](https://jobjo.github.io/2019/04/24/ocaml-has-some-new-shiny-syntax.html)), however, it seems like there is no `;`-sequencing.
Next best thing seemed to be [ppx_let](https://opam.ocaml.org/packages/ppx_let/) but it somehow constrains `ppx_import` via some dependency if I try to install it: `downgrade ppx_import      1.6.2 to 1.5`.
I then tried [ocaml-monadic](https://opam.ocaml.org/packages/ocaml-monadic/) which seems to work and the syntax is ok; I'll adjust the files later.
