### ISSUE TITLE
Goblint crashes with "ill-typed program" on sqlite

### ISSUE THREAD

**Issue by jerhard** [goblint/analyzer#813]
Starting with e73ee0351db087ad0ef827e6fe6c92d4abddb29e, Goblint crashes on sqlite (`sqlite-amalgamation-3370200`). Goblint crashes on line 32088 of sqlite3.c, a line following a call to `memcpy`. 

Command-line:
```
 ./goblint ../bench-repos/sqlite-amalgamation-3370200/sqlite3.c ../bench-repos/sqlite-amalgamation-3370200/sqlite3.h ../bench-repos/sqlite-amalgamation-3370200/sqlite3ext.h ../bench-repos/sqlite-amalgamation-3370200/shell.c -v --set pre.cppflags[+] -DSQLITE_DEBUG --disable ana.base.context.non-ptr --disable sem.unknown_function.spawn --set ana.thread.domain plain --enable exp.earlyglobs --set ana.base.privatization none --set pre.cppflags[+] -DGOBLINT_NO_BSEARCH --set pre.cppflags[+] -DGOBLINT_NO_ASSERT --set result json-messages -v
```

<details>
  <summary>Stack trace</summary>

[Error][Analyzer] About to crash! (/home/julian/Entwicklung/Programm_Analyse/bench-repos/sqlite-amalgamation-3370200/sqlite3.c:32088:3-32088:85)

runtime: 00:00:03.187
vars: 2133, evals: 3049

|rho|=2133
|called|=297
|stable|=1808
|infl|=1477
|wpoint|=21
Found 39 contexts for 34 functions. Top 5 functions:
4	contexts for entry state of sqlite3_config on /home/julian/Entwicklung/Programm_Analyse/bench-repos/sqlite-amalgamation-3370200/sqlite3.c:167020:2-167325:1
2	contexts for entry state of sqlite3_str_append on /home/julian/Entwicklung/Programm_Analyse/bench-repos/sqlite-amalgamation-3370200/sqlite3.c:29908:2-29920:1
2	contexts for entry state of enlargeAndAppend on /home/julian/Entwicklung/Programm_Analyse/bench-repos/sqlite-amalgamation-3370200/sqlite3.c:29896:1-29902:1
1	contexts for entry state of sqlite3MemSetDefault on /home/julian/Entwicklung/Programm_Analyse/bench-repos/sqlite-amalgamation-3370200/sqlite3.c:24791:1-24803:1
1	contexts for entry state of sqlite3PCacheSetDefault on /home/julian/Entwicklung/Programm_Analyse/bench-repos/sqlite-amalgamation-3370200/sqlite3.c:51903:1-51920:1

Memory statistics: total=3308.89MB, max=305.32MB, minor=3239.24MB, major=324.49MB, promoted=254.85MB
    minor collections=1553  major collections=14 compactions=0

vars = 2133    evals = 3049  

Timings:
TOTAL                           1.234 s
  parse                           0.455 s
  convert to CIL                  0.657 s
  mergeCIL                        0.123 s
  analysis                        0.000 s
    createCFG                       0.864 s
      handle                          0.308 s
      iter_connect                    0.499 s
        computeSCCs                     0.225 s
    global_inits                    0.357 s
    solving                         0.410 s
      S.Dom.equal                     0.005 s
Timing used
Memory statistics: total=3308.90MB, max=305.32MB, minor=3239.26MB, major=324.49MB, promoted=254.85MB
    minor collections=1553  major collections=14 compactions=0

Fatal error: exception Failure("ill-typed program")
Raised at Stdlib.failwith in file "stdlib.ml", line 29, characters 17-33
Called from Base.MainFunctor.invariant.inv_exp.invert_binary_op in file "src/analyses/base.ml", line 1981, characters 23-46
Called from Base.MainFunctor.invariant in file "src/analyses/base.ml", line 2079, characters 8-33
Called from Base.MainFunctor.branch.refine in file "src/analyses/base.ml", line 2194, characters 16-83
Called from MCP.MCP2.branch.f in file "src/analyses/mCP.ml", line 233, characters 17-35
Called from MCP.MCP2.map_deadcode.one_el in file "src/analyses/mCP.ml", line 100, characters 49-78
Called from Stdlib__List.fold_left in file "list.ml", line 121, characters 24-34
Called from MCP.MCP2.map_deadcode in file "src/analyses/mCP.ml", line 101, characters 13-35
Called from MCP.MCP2.branch in file "src/analyses/mCP.ml", line 235, characters 15-52
Called from Constraints.WidenContextLifterSide.lift_fun in file "src/framework/constraints.ml", line 344, characters 25-41
Called from Constraints.PathSensitive2.map.h in file "src/framework/constraints.ml", line 952, characters 16-36
Called from BatSet.Concrete.fold in file "src/batSet.ml", line 310, characters 35-56
Called from Constraints.PathSensitive2.map in file "src/framework/constraints.ml", line 955, characters 12-43
Called from Constraints.DeadCodeLifter.lift_fun in file "src/framework/constraints.ml", line 415, characters 13-29
Called from Constraints.HashconsLifter.branch in file "src/framework/constraints.ml", line 56, characters 14-38
Called from Constraints.FromSpec.tf_test in file "src/framework/constraints.ml", line 579, characters 20-39
Called from Constraints.FromSpec.tf in file "src/framework/constraints.ml", line 655, characters 4-552
Called from BatList.fold_left2 in file "src/batList.mlv", line 660, characters 39-54
Called from Constraints.FromSpec.tf in file "src/framework/constraints.ml", line 679, characters 4-107
Called from BatList.map in file "src/batList.mlv", line 239, characters 23-28
Called from Constraints.FromSpec.system.tf in file "src/framework/constraints.ml", line 704, characters 27-47
Called from Constraints.EqConstrSysFromGlobConstrSys.conv in file "src/framework/constraints.ml", line 805, characters 4-105
Called from Td3.WP.solve.solve in file "src/solvers/td3.ml", line 138, characters 22-47-25
[shortened]
</details>

**Comment by sim642** [comment]
On `interactive` there's actually a more conservative implementation for `memcpy` which doesn't try to copy, but just invalidates:
https://github.com/goblint/analyzer/blob/9dd1ded153a71ba04f7f5e27dc5286f722aef8a4/src/analyses/base.ml#L2509-L2526

Maybe treating it as an assignment doesn't always do the right thing?

**Comment by jerhard** [comment]
I added a [test case](https://github.com/goblint/analyzer/blob/2bc66f36fe9c019dceaa001aa9a5a061dae25abe/tests/regression/02-base/90-memcpy.c) that produces this crash.  There (like in the original sqlite code), a `double` is copied into an `unsigned long long`.

**Comment by sim642** [comment]
Indeed, `memcpy` can be abused for all sorts of non-array things, so we should probably be more careful about trying to actually implement the copying and in all other cases do the invalidation instead.

**Comment by jerhard** [comment]
The line that Goblint crashed on is actually something that gets translated into a conditional. The `failwith` is executed because of some apparent inconsistency of integer and floating point values in the conditional. The problem seems to be that an `unsigned long`  contains a `double` abstract value in the conditional.
