### ISSUE TITLE
Non-unique thread spawns

### ISSUE THREAD

**Issue by sim642** [goblint/analyzer#843]
In some special cases it's desirable to spawn threads as non-unique right off the bat:
1. Unknown functions which spawn create unique threads: https://github.com/goblint/analyzer/pull/837#discussion_r984570708. This is unsound and we should instead create the new thread immediately as non-unique.
2. Klever stubs have a non-unique thread spawning function: https://github.com/goblint/analyzer/pull/688#discussion_r851624003.

An extra uniqueness argument needs to be added and passed from `ctx.spawn` to the threadid analysis through the numerous transfer functions involved.

**Comment by michael-schwarz** [comment]
Unassigning myself as I currently do not plan on working on this the next few months.
