### ISSUE TITLE
`space` option for TD3 incompatible with removal of wpoints & `sides-local` widening strategy

### ISSUE THREAD

**Issue by michael-schwarz** [goblint/analyzer#867]
Helmut observed that those do not work together, as `space` stores values only for things that are in `point`.
We should include a check that these configuration options are mutually exclusive.

**Comment by sim642** [comment]
By the way, in #796 I added the option `solvers.td3.remove-wpoint`: 3ea59f7dfcc316f4b42781c70369e1a35ee2d348. So if relevant, that can be just cherry-picked.
