### ISSUE TITLE
Some observations from SV-comp runs (To be split into separate issues)

### ISSUE THREAD

**Issue by michael-schwarz** [goblint/analyzer#879]
I made a run of all of sv-comp with 15min timeout and our config and here are some observations that we might want to think about:

**Resolved**

- ~~31 tasks (all with expected verdict true) fail after the actual analysis is already over and the verdict printout is produced with the exception~~ (fixed by #882)

- ~~2 instances where the analysis succeeds, but some time later a Not_found exception is produced~~ (fixed by #882)

**PR exists**

- ~~A lot of recursive runs still go out of memory despite the interval contexts being disabled. At the same time, apron is enabled though and I'm not sure if anything smart is done there to prevent the issue of infinite contexts happening within the apron domain then. (maybe @leunam99 can advise here?)~~ (no noticeable impact, but with #883 it is more consistent)

**Dedicated issue exists**

- Total of 11 instances of #118

**Open**

- We run out of memory on our own task https://gitlab.com/sosy-lab/benchmarking/sv-benchmarks/-/blob/main/c/goblint-regression/04-mutex_05-lockfuns.c. It seems the issue is due to `mutex-meet` privatization being the default for octagons, and the autotuner enabling Apron. In this configuration, `side_widen` would need to be `sides-pp`. It seems there is only one such task though where we run out of memory though, so it probably is not much of an issue.

- Also for this task, autoconf enables octagons for the following variables: What seems odd is that it is activated for `__builtin_bswap64` and what these `val` variables for which it is also enabled. (#921)

> Enabled octagon domain for:
__builtin_bswap64, myglobal, id, __x, top, __x, __x, __x, i, key, count, a, tmp, count, i, j, i___0, j___0, k, size, r, val, val, val, val, val, val, val, val, val, val, val, val, val, val

- [ ] One test fails with `Apron.Manager.Error`: https://gitlab.com/sosy-lab/benchmarking/sv-benchmarks/-/blob/main/c/ldv-linux-3.16-rc1/43_2a_consumption_linux-3.16-rc1.tar.xz-43_2a-drivers--nfc--st21nfca--st21nfca_i2c.ko-entry_point.cil.out.c

> __VERIFIER_nondet_int, ldv_malloc, tmp, arg0, arg1, ret_val, tmp, tmp, tmp, tmp, tmp, tmp, tmp, tmp, tmp, tmp, tmp, tmp, tmp, tmp, tmp, tmp, skb, arg0, tmp, tmp, skb, is_lock, tmp, ldv_func_arg1, handler, thread_fn, ldv_func_arg7, ldv_func_res, ldv_func_arg2, ldv_func_arg5, ldv_func_arg6, flags, ldv_func_arg1, ldv_func_arg2, ldv_func_arg3, tmp, flags, ldv_func_arg1, ldv_func_arg2, ldv_func_arg3, tmp, flags, ldv_func_arg1, ldv_func_arg2, tmp, flags, ldv_func_arg1, ldv_func_arg2, tmp, flags, ldv_func_arg1, ldv_func_arg2, tmp, flags, ldv_func_arg1, tmp, flags, ldv_func_arg1, tmp, flags, ldv_func_arg1, ldv_func_arg2, ldv_func_arg3, tmp, flags, size, tmp, ldv_func_arg1, handler, thread_fn, ldv_func_arg7, ldv_func_res, ldv_func_arg2, ldv_func_arg5, ldv_func_arg6, tmp___4, tmp___5, tmp___6, tmp___7, ldvarg1, tmp, ldvarg3, tmp___0, tmp, state, line, data, tmp, state, line, data, tmp, dev, line, data, line, dev, line, data, line, tmp, tmp, tmp___0, r, phy, client, tmp, tmp___0, tmp___1, tmp___3, r, phy, irq, client, phy, r, irq, tmp, tmp___0, tmp___1, tmp___2, phy, skb, r, i, __len, tmp___1, skb, i, j, r, size, len, buflen, j, r, skb, i, tmp___0, tmp___1, tmp___2, skb, skb, tmp, tmp___0, tmp___1, tmp___2, phy, phy, r, i, size, priority, tmp, gpio, tmp, gpio, value, gpio, tmp___0, gpio, value, tmp, tmp___0, gpio, tmp, tmp___0, adap, func, adap, tmp, data, tmp, dev, data, dev, size, tmp, exp, tmp, tmp, size, p, tmp, tmp___0, size, p, tmp, tmp___0, top, __x, __x, __x, i, key, count, a, tmp, count, i, j, i___0, j___0, k, size, r, val, val, val, val, val, val, val, val, val, val, val, val, val, val
SV-COMP specification: CHECK( init(main()), LTL(G ! call(reach_error())) )
[Error][Analyzer] About to crash!
> Fatal error: exception Apron.Manager.Error
 {  exn = Exc_invalid_argument; funid = Funid_forget_array;
  msg = unknown variable tmp#3041 in the environment; }
  
-  6 tasks crash with various error messages (but no error message does not directly reference #118)

![other1](https://user-images.githubusercontent.com/13812333/199988114-42ab7d17-b461-4408-8b69-5f68ba66ba21.png)
![other2](https://user-images.githubusercontent.com/13812333/199988406-455045bc-ec0d-40b0-bb82-78b8cb3b60f1.png)

- 5 new instances of incompatible ikinds

![ikind](https://user-images.githubusercontent.com/13812333/199447586-b7f650e3-870a-4d55-a262-74e9b10d8a7e.png)

- We should investigate which warnings to print, there is a task where printing takes over 2 minutes and allocates so much memory that we run out of RAM :/

**Comment by michael-schwarz** [comment]
Since the relevant logfiles etc are too large, here's a link to them: https://syncandshare.lrz.de/getlink/fiJfaPCw85pK1aB9e87JB1/

**Comment by sim642** [comment]
This is lower priority, but in Juliet no-overflow tasks that might get included ([sv-benchmarks MR](https://gitlab.com/sosy-lab/benchmarking/sv-benchmarks/-/merge_requests/1369)), we seem to do a bit poorly: https://goblint.cs.ut.ee/results/02-all-fast-no-overflow-juliet2/table-generator.table.html#/table?filter=id_any(value(Juliet)). We only solve 2056/6156, although there's another 1022 true tasks.

All of these are very small and simple, but we might just be missing some library functions.

**Comment by michael-schwarz** [comment]
I think everything we want to do for this year has been transferred to separate issues that are now resolved, so closing this.
