### ISSUE TITLE
Refine congruence information on `x % 2 != 0`

### ISSUE THREAD

**Issue by jerhard** [goblint/analyzer#892]
Currently, no special refinement is performed for the congruences domain when encountering an inequality. Implementing refinement for the general case of inequalities `x % d = c`   would require something like congruence sets, but for the case where `d = 2`, the information is expressible in the domain and should be used.
There seem to be two SV-Comp benchmarks affected by this: `c/array-examples/sanfoundry_24-1.i` and 
`sv-benchmarks/c/array-examples/sanfoundry_24-2.i`.

**Comment by sim642** [comment]
It generalizes slightly to higher divisors as well. For example if `x` is `3Z+1` and there's a branch on `x % 3 != 1`, then we'd be excluding the only possible option, thus making the branch dead.
