### ISSUE TITLE
Unsoundness for one additional sv-comp task

### ISSUE THREAD

**Issue by michael-schwarz** [goblint/analyzer#917]
We have a new unsoundness that I uncovered after running with more than 2GB of memory limit:

- [x] `c/ldv-linux-4.2-rc1/linux-4.2-rc1.tar.xz-08_1a-drivers--block--loop.ko-entry_point.cil.out.yml`

**Comment by sim642** [comment]
This must be a new Goblint bug, because the last prerun at 23d264578 didn't have this with a 7GB memory limit.

**Comment by michael-schwarz** [comment]
Not sure, that pre-run was without loop unrolling. It could just as well be one of the cases where the bug only reveals itself after unrolling loops (like most of the other ldv ones).

**Comment by michael-schwarz** [comment]
Last year, Infer and Crux claim to have solved this task, but I am not sure how confident we should be in their votes.

https://sv-comp.sosy-lab.org/2022/results/results-verified/unreach-call.SoftwareSystems-DeviceDriversLinux64-ReachSafety.table.html#/table?filter=id_any(value(linux-4.2-rc1.tar.xz-08_1a-drivers--block--loop.ko-entry_point.cil.out.yml))

**Comment by michael-schwarz** [comment]
1. Call to main()
 2. `ldv_state_variable_0 = 1;`
 3. Assume `tmp____23` = `9` and `tmp___31` = `1`
 4. Call to `loop_init()` in l. 8102
        - `ldv_misc_register_17` returns a non-det int via `misc_register` (assume `0`)
        - `register_blkdev` returns a non-det int (assume `0`)
        - call to `loop_init()` returns `0` value
    `ldv_state_variable_5 = 1;` in l.8110
    `ldv_initialize_block_device_operations_5` sets `lo_fops_group0` to be completely zero-initialized
    `ldv_initialize_loop_func_table_11` sets `xor_funcs_group0` to be completely zero-initlaized
5. Jump to `ldv_36952` (via `ldv_36937` -> `ldv_36898`)
6. Assume `tmp___23` = `11` and `tmp___33` = `1`
7. Call to `lo_ioctl` with pointer to lo_fops_group0 (zero initialized memory) as `bdev` in l. 8164
8. Dereferencing `(struct loop_device *)(bdev->bd_disk)->private_data;` dereferences a null pointer


Thus, because of missing initialization of `lo_fops_group0`, the task contains undefined behavior, and the unreach-call verdict is not meaningful here.

**Comment by michael-schwarz** [comment]
Fixed in https://gitlab.com/sosy-lab/benchmarking/sv-benchmarks/-/merge_requests/1415
