### ISSUE TITLE
Empty functions marked `noreturn` cause crash

### ISSUE THREAD

**Issue by just-max** [goblint/analyzer#951]
```c
#include <stdnoreturn.h>

noreturn void foo() {
  // empty
}

...
```

<details>
<summary>Backtrace</summary>

```
Fatal error: exception Failure("hd")
Raised at Stdlib.failwith in file "stdlib.ml", line 29, characters 17-33
Called from Goblint_lib__CfgTools.createCFG.(fun) in file "src/framework/cfgTools.ml", line 229, characters 39-66
Called from Stdlib__List.iter in file "list.ml", line 110, characters 12-15
Called from GoblintCil__Cil.iterGlobals in file "src/cil.ml", line 5651, characters 2-29
Called from Goblint_lib__CfgTools.createCFG in file "src/framework/cfgTools.ml", line 218, characters 2-1023
Called from Goblint_lib__CfgTools.createCFG in file "src/framework/cfgTools.ml" (inlined), line 453, characters 16-49
Called from Goblint_lib__CfgTools.getCFG in file "src/framework/cfgTools.ml", line 580, characters 19-33
Called from Goblint_lib__Control.compute_cfg in file "src/framework/control.ml", line 704, characters 19-39
Called from Goblint_lib__Control.analyze in file "src/framework/control.ml", line 710, characters 21-37
Called from Goblint_lib__Maingoblint.do_analyze.control_analyze in file "src/maingoblint.ml", line 460, characters 10-46
Re-raised at Goblint_lib__Maingoblint.do_analyze.control_analyze in file "src/maingoblint.ml", line 473, characters 8-49
Called from Dune__exe__Goblint.main in file "src/goblint.ml", line 62, characters 6-35
Called from Stdlib.at_exit.new_exit in file "stdlib.ml", line 560, characters 59-63
Called from Stdlib.do_at_exit in file "stdlib.ml" (inlined), line 566, characters 20-61
Called from Std_exit in file "std_exit.ml", line 18, characters 8-20
```

</details>

**Comment by michael-schwarz** [comment]
Thanks for flagging this! Did you check that it is only the case for functions marked `noreturn`, or does e.g. adding an arbitrary attribute suffice to cause this issue?

**Comment by just-max** [comment]
Using `__attribute__((noreturn))` does the same thing, other attributes (e.g. `__attribute__((const))`) don't cause any issues.

The only other [_function specifier_](https://en.cppreference.com/w/c/language/function_specifiers) (`inline`) does not cause any issues, so it's not that.

**Comment by michael-schwarz** [comment]
The issue seems to be that we always assume `fd.sbody.bstmts` to be non-empty, which is generally the case as functions will contain a `return` statement (or we artificially insert one in CIL if it is not there), but don't do this for `noreturn` functions.

**Comment by sim642** [comment]
Adding a pseudo return should work for now, although we might want to rethink it in CIL. Maybe CIL shouldn't try to be so clever and have special handling for `noreturn` or `abort`/`exit`/etc functions, but always have a return node. It would actually simplify things a lot on the Goblint side, especially when it comes to incremental comparisons, updates and solving, where we've repeatedly required workaround for our pseudo returns. If they weren't pseudo, but came normally from CIL, many of these issues disappear.
