### ISSUE TITLE
Reluctant incremental Goblint does not reach fixpoint on some commits of chrony

### ISSUE THREAD

**Issue by jerhard** [goblint/analyzer#959]
When performing a reluctant incremental analysis with Goblint ([interactive_benchmarks](https://github.com/goblint/analyzer/tree/interactive_benchmarks), [ee720d4](https://github.com/goblint/analyzer/commit/ee720d46f6e8633e111f73049eb46c8c353e8898)) on some commits of  chrony the reluctant incremental analysis does not reach the fixpoint. 

The issue is potentially related to the treatment of functions with changed headers.

## How to reproduce

Example on `chrony`, where the incremental does not reach a fixpoint:

Parent: 
`7a80647fb44a733ba5895898003376c319aea888`

Command line:
`./goblint --conf conf/custom/chrony.json -v --disable incremental.load --enable incremental.save ../chrony `

Child (For Reluctant reanalysis):
`5f4cbaab7e0e01c165fff657f2b53489c949fee4`

Command line:

`./goblint --conf conf/custom/chrony-incrpostsolver.json -v --enable incremental.load --disable incremental.save --enable incremental.reluctant.enabled ../chrony `

Before each run of Goblint, the compile db has to be created in the `chrony` directory with this [script](https://github.com/goblint/bench/blob/24d7a9b2f6d5a21efb668bbaab78b22c0630b167/scripts/incremental/build/build_compdb_chrony.sh).

### Further Information
There are 38 cases on parent-child commit pairs on `chrony` where the reluctant incremental analysis has an unreached fixpoint. It is not easy to identify common characteristics of those commits that may give a hint whether some specific treatment is going wrong. 
There are some cases the reluctant analysis fail where the header of a function is changed, but this does not apply to the [(rather small) patch](https://github.com/mlichvar/chrony/commit/5f4cbaab7e0e01c165fff657f2b53489c949fee4) given in the example.

Analyzer log:
[analyzer.log](https://github.com/goblint/analyzer/files/10287043/analyzer.log)

Excerpt from unreached fixpoint:
```
Fixpoint not reached at node 69364 "(unsigned int )my_mode == 3U" on chrony/ntp_core.c:971:7-971:29
 Solver computed: [....]
[....] because {my_mode, my_mode}:
 not leq {0, smooth_time} because Set (exp): {my_mode, my_mode} not leq {0, smooth_time}
   because my_mode
 . 

```

</details>

**Comment by jerhard** [comment]
A reproced case with the right Goblint version:

```
{"hash": "ff9301567e2702f2790bef14963975f99a96f766", "parent_hash": "e7a254265f0c26c80fa1c04beb9eb14064f97d2f", "CLOC": 22, "relCLOC": 22, "failed": true}
```

**Comment by sim642** [comment]
```
Set (exp): {my_mode, my_mode} not leq {0, smooth_time}
```
I believe these are var_eq analysis partitions, representing `my_mode == my_mode` and `0 == smooth_time`. I see that the chrony conf makes var_eq context insensitive, which might have something to do with this.
The fact that there's an explicit identity partition seems odd. I guess if it were properly simplified away, the `leq` might hold.

**Comment by michael-schwarz** [comment]
Unfortunately, the same issue happens without `var_eq` as well.

**Comment by jerhard** [comment]
Commit with very minimal changes causing this:
{"hash": "1e727c4497dd028e4ea4f32fc3298e4bd580c68a", "parent_hash": "83010590af1e3a4e317d14747e5f643879701e45", "CLOC": 2, "relCLOC": 2, "failed": true}

**Comment by jerhard** [comment]
Another commit with rather small changes:
99e3c67a8104864300cebf58fdf6a7cece99c8c2
parent:
83010590af1e3a4e317d14747e5f643879701e45

**Comment by jerhard** [comment]
>Commit with very minimal changes causing this:
{"hash": "1e727c4497dd028e4ea4f32fc3298e4bd580c68a", "parent_hash": "83010590af1e3a4e317d14747e5f643879701e45", "CLOC": 2, "relCLOC": 2, "failed": true}

Looking at this with @stilscher, we found that for this commit, turning off the incremental postsolver did remove the warning about the unreached fixpoint. Maybe the problem is in the interplay between the reluctant analysis and the incremental postsolver.

**Comment by jerhard** [comment]
I tried again deactivating some options, to see if there is an impact on the fixpoint issue. I now found that at least for one parent-child commit pair, the fixpoint is not reached in the child, even when changing some configurations regarding partial-contexts and deactivating the incremental postsolver. 

On the commit pair:
```
PARENT=e7a254265f0c26c80fa1c04beb9eb14064f97d2f
CHILD=ff9301567e2702f2790bef14963975f99a96f766
```

with this configuration: [chrony-incrpostsolver.txt](https://github.com/goblint/analyzer/files/10290808/chrony-incrpostsolver.txt) (rename to .json for it to work; Github won't allow json files here)]

where:
- ana.base.context.non-ptr: true
- var_eq is removed
- incremental.postsolver.enabled: false
- incremental.restart.write-only: false 

The fixpoint is not reached.

**Comment by jerhard** [comment]
[Here](https://github.com/jerhard/test-commits/blob/master/test-commits.sh) is a script that can be run to automatically execute the steps to run Goblint on the parent and child commit. The script assumes to be executed from a sibling folder of `chrony` and `analyzer`.

**Comment by jerhard** [comment]
I changed the implementation in td3 that calls the postsolver with 
```
      Post.post st (!reluctant_vs @ vs) rho;
```
to instead only append !reluctant_vs if the incremental postsolver is on.

```
      let additional_vars =
        if GobConfig.get_bool "incremental.postsolver.enabled" then !reluctant_vs else []
      in
      Post.post st (additional_vars @ vs) rho;
```

 I then ran with the non-incremental postsolver, and the fixpoint issue did not show up for commits: PARENT=`e7a254265f0c26c80fa1c04beb9eb14064f97d2f`
CHILD=`ff9301567e2702f2790bef14963975f99a96f766`.

I am not sure though whether the non-incremental postsolver then does all the necessary checks or whether it then is missing some checks.

**Comment by sim642** [comment]
The non-incremental postsolver always does a full pass, so it should be checking everything necessary and emitting also all the reached warnings.

Although it's surprising that `reluctant_vs` would be the problem because they are reluctant variables, which _are not_ destabilized, so the check should still pass for them.
Or maybe it's somehow related to `cheap_full_reach`, which also uses `reluctant_vs` and already is conditional on `incr_verify`.

**Comment by jerhard** [comment]
I looked again at the [small commit](hhttps://github.com/mlichvar/chrony/commit/1e727c4497dd028e4ea4f32fc3298e4bd580c68a) which is now easier to debug, thanks to @stilscher 's patch to the [compile db script](https://github.com/goblint/bench/blob/bfc219a31a99474716f063becf76bb96590e2a04/scripts/incremental/build/build_compdb_chrony.sh) for chrony. (It avoids that some macro in chrony's config.h is set differently after each configure.)


Analyzing the chlid commit with reluctant analysis, the  postsolver reports that the fixpoint is not reached. 

Earlier in the output, the following is reported about the reluctant solving phase :
```
Separately solving changed functions...
test for call of SRC_ResetInstance (27025)
in infl after solving: node 27777 "n_sources ++;"
Destabilization not required...
test for call of SRC_ResetInstance (27025)
in infl after solving: node 57320 "! ntp_only"
Destabilization not required...
test for call of SRC_CreateNewInstance (27019)
Further destabilization happened ...
Final solve...
```
The function `SRC_ResetInstance` is analyzed reluctantly (twice, for different calling contexts), and for both instances no destabilization is required. Thus, they are added to `reluctant_vs`.

Then, the function  `SRC_CreateNewInstance` is analyzed reluctantly, but further destabilization was required.  

Later, the (non-incremental) postsolver reports that the fixpoint is not reached for the return node of `SRC_ResetInstance`. No fixpoint issue is reported when `!reluctant` is not passed to the postsolver. 

My hypothesis is that the calls to `SRC_ResetInstance` that were reluctantly analyzed are actually no longer reachable, and that the solver did not compute a fixpoint for them. This would explain why the (non-incremental) postsolver does not complain when `reluctant_vs` is not explicitly passed to it.

<details>
<summary>Reluctant solving</summary>

```
change_info = { unchanged = 8052; changed = 2; added = 0; removed = 0 }
Completely changed function: SRC_ResetInstance
Completely changed function: SRC_CreateNewInstance
Removing data for changed and removed functions...
Data after clean-up:
|rho|=62455
|stable|=62455
|infl|=58902
|wpoint|=0
|side_dep|=12297
|side_infl|=32750
|var_messages|=4
|rho_write|=26217
|dep|=49949
Separately solving changed functions...
test for call of SRC_ResetInstance (27025)
in infl after solving: node 27777 "n_sources ++;"
Destabilization not required...
test for call of SRC_ResetInstance (27025)
in infl after solving: node 57320 "! ntp_only"
Destabilization not required...
test for call of SRC_CreateNewInstance (27019)
Further destabilization happened ...
Final solve...

[.... omitted ... ]
```

</details>

<details>
<summary> Fixpoint </summary>

```
!reluctant_vs:
call of SRC_ResetInstance (27025) on /home/julian/Entwicklung/Programm_Analyse/chrony/sources.h:74:13-74:53
call of SRC_ResetInstance (27025) on /home/julian/Entwicklung/Programm_Analyse/chrony/sources.h:74:13-74:53
end of !reluctant_vs
Postsolving

Fixpoint not reached at node 89460 "return;" on /home/julian/Entwicklung/Programm_Analyse/chrony/sources.c:303:1-303:1
 Solver computed:
 {([Unit:(), Reversed (top or Set (varinfo)):{},
    top or Set (Set (exp)):{{result, instance}}, Reversed (top or Set (exp)):{},
    Unit:(), Reversed (top or Set (Normal Lvals * booleans)):{}, Unit:(),
    Unit:(), top or Set (variables):{line}, booleans:False,
    MT mode:Singlethreaded, Thread * lifted created and Unit:(main, bot),
    value domain * array partitioning deps * Vars with Weak Update * Unit:(mapping {
                                                                             Parameter {
                                                                               instance ->
                                                                                 {&((alloc@sid:27747@tid:main(#top)), /home/julian/Entwicklung/Programm_Analyse/chrony/sources.c:229:3-229:87)}
                                                                             }
                                                                           }, mapping {
                                                                                  }, {}, ()),
    top or std * lifted node:(mapping {
                                }, Unknown node), Unit:()], mapping {
                                                              })}
 Right-Hand-Side:
 {([Unit:(), Reversed (top or Set (varinfo)):{}, top or Set (Set (exp)):{},
    Reversed (top or Set (exp)):{}, Unit:(),
    Reversed (top or Set (Normal Lvals * booleans)):{}, Unit:(), Unit:(),
    top or Set (variables):{line}, booleans:False, MT mode:Singlethreaded,
    Thread * lifted created and Unit:(main, bot),
    value domain * array partitioning deps * Vars with Weak Update * Unit:(mapping {
                                                                             Parameter {
                                                                               instance ->
                                                                                 {&((alloc@sid:27747@tid:main(#top)), /home/julian/Entwicklung/Programm_Analyse/chrony/sources.c:229:3-229:87)}
                                                                             }
                                                                           }, mapping {
                                                                                  }, {}, ()),
    top or std * lifted node:(mapping {
                                }, Unknown node), Unit:()], mapping {
                                                              })}
 Difference: ([Unit:(), Reversed (top or Set (varinfo)):{},
               top or Set (Set (exp)):{}, Reversed (top or Set (exp)):{},
               Unit:(), Reversed (top or Set (Normal Lvals * booleans)):{},
               Unit:(), Unit:(), top or Set (variables):{line}, booleans:False,
               MT mode:Singlethreaded,
               Thread * lifted created and Unit:(main, bot),
               value domain * array partitioning deps * Vars with Weak Update * Unit:(mapping {
                                                                                        Parameter {
                                                                                          instance ->
                                                                                            {&((alloc@sid:27747@tid:main(#top)), /home/julian/Entwicklung/Programm_Analyse/chrony/sources.c:229:3-229:87)}
                                                                                        }
                                                                                      }, mapping {
                                                                                             }, {}, ()),
               top or std * lifted node:(mapping {
                                           }, Unknown node), Unit:()], mapping {
                                                                         }):
 not leq ([Unit:(), Reversed (top or Set (varinfo)):{},
           top or Set (Set (exp)):{{result, instance}},
           Reversed (top or Set (exp)):{}, Unit:(),
           Reversed (top or Set (Normal Lvals * booleans)):{}, Unit:(), Unit:(),
           top or Set (variables):{line}, booleans:False,
           MT mode:Singlethreaded, Thread * lifted created and Unit:(main, bot),
           value domain * array partitioning deps * Vars with Weak Update * Unit:(mapping {
                                                                                    Parameter {
                                                                                      instance ->
                                                                                        {&((alloc@sid:27747@tid:main(#top)), /home/julian/Entwicklung/Programm_Analyse/chrony/sources.c:229:3-229:87)}
                                                                                    }
                                                                                  }, mapping {
                                                                                         }, {}, ()),
           top or std * lifted node:(mapping {
                                       }, Unknown node), Unit:()], mapping {
                                                                     }) because {result, instance}:
 .```

</summary>

**Comment by jerhard** [comment]
>My hypothesis is that the calls to SRC_ResetInstance that were reluctantly analyzed are actually no longer reachable, and that the solver did not compute a fixpoint for them. This would explain why the (non-incremental) postsolver does not complain when reluctant_vs is not explicitly passed to it.

I think it should work to only pass those unknowns from  `!reluctant_vs` to the postsolver that are `stable`.
