### ISSUE TITLE
Goblint server mode crashes with unexpected requests

### ISSUE THREAD

**Issue by FeldrinH** [goblint/analyzer#983]
Goblint server mode seems to be very prone to crashing when presented with unexpected requests. This is problematic for GobPie because it means the server has to be restarted, which means all analysis needs to be run again with no way to reuse previous results.

So far I have encountered crashes in the following cases:

- [x] `analyze` when there is a syntax error in the C code crashes with `Parsing errorFatal error: exception GoblintCil__Frontc.ParseError("Parse error")`
- [x] `analyze` when config has not been loaded crashes with `Fatal error: exception Failure("No suitable function to start from.")`. (In GobPie this can happen when running an analysis with an invalid goblint.json file.)
- [x] `node_state` with a node id that does not exist in the analysis results crashes the server with `Fatal error: exception Not_found`. (In GobPie this can happen when requesting node state for a node in the CFG of a function that is never called.)
- [x] `node_state` when analysis has not run crashes with `Fatal error: exception File "src/framework/control.ml", line 45, characters 76-82: Assertion failed`. (This should not be possible in current GobPie but it could happen if the rules around running analyses and restarting are changed.)
- [x] `functions` when analysis has not run crashes with `Fatal error: exception Invalid_argument("Option.get")`. (This should not be possible in current GobPie but it could happen if the rules around running analyses and restarting are changed.)

The last three are particularly problematic because they can crash the server while running a request that should only read data and thus one might reasonably expect them to never affect the server in any way.

(All issues encountered with Goblint built from commit 3d4e7addd628ddcdb21e4849c7cdf9eaa3dd6c50)

**Comment by michael-schwarz** [comment]
Most of these should potentially be quite easy to fix by catching the appropriate exceptions in `server.ml` and returning appropriate error messages via json-RPC.
